// PropBetEdge Golf product pages. Pure functions over the public projection (never premium data).
import {e,a,go,kicker,toPar,pos,dates,division,tourLabel,statusLabel,coverageLabel,portrait,courseImage,pill,conf,heading,section,stat,fmtDate} from './ui.js';
const DIM_LABELS={scoring:'Scoring vs field',consistency:'Consistency',under_par:'Under-par rounds',cuts:'Cuts made',top10:'Top-10 rate',contention:'Contention (top 5)',form:'Recent form',majors:'Major performance'};
const SERIES=[['masters','Masters Tournament','men'],['pga-championship','PGA Championship','men'],['us-open','U.S. Open','men'],['the-open','The Open Championship','men'],['chevron','Chevron Championship','women'],['us-womens-open','U.S. Women’s Open','women'],['womens-pga','Women’s PGA Championship','women'],['evian','The Evian Championship','women'],['womens-open','Women’s Open','women'],['players','The Players Championship','men']];
export const seriesName=k=>SERIES.find(s=>s[0]===k)?.[1]||k;
const attribution=`<p class="source-note">Results, fields and course setups adapted from Wikipedia articles (CC BY-SA 4.0; the redistributed results dataset is available under the same licence). Identities, championship editions and venues from Wikidata (CC0). Photographs from Wikimedia Commons with per-image credit. ${a('/intelligence#sources','Sources & methodology')}</p>`;
const freshness=ix=>`<div class="data-source" data-asof="${e(ix.as_of)}"><span>Projection ${e(ix.as_of?.slice(0,16).replace('T',' '))} UTC</span><span>${e(ix.coverage.editions_with_leaderboards)} leaderboards · ${e(ix.coverage.rounds.toLocaleString('en-US'))} rounds · ${e(ix.coverage.players.toLocaleString('en-US'))} players</span><span>Live scoring not connected</span><span data-freshness role="status">Archive + schedule data</span></div>`;
const playerLink=(p,cls='player-link')=>p?.slug?`<a class="${cls}" href="/player/${e(p.slug)}">${e(p.name)}</a>`:e(p?.name||'—');
const edLink=x=>`<a href="/tournament/${e(x.slug)}">${e(x.name)}</a>`;
function eventCard(x,{big=false}={}){
 return `<article class="event-card${big?' event-card-big':''}" data-division="${e(x.division)}" data-major="${x.is_major}" data-year="${e(x.year)}"><div class="event-card-top">${pill(x.is_major?(x.division==='women'?'Women’s major':'Men’s major'):tourLabel(x),x.division==='women'?'pill-women':'pill-men')}${pill(statusLabel(x.status),'pill-'+x.status)}</div><h3>${edLink(x)}</h3><p class="event-meta">${e(dates(x))}${x.course?` · <a href="/course/${e(x.course.slug)}">${e(x.course.name)}</a>`:x.location?` · ${e(x.location)}`:''}</p>${x.winner?`<div class="event-winner">${portrait(x.winner,{size:48,cls:'mini-portrait'})}<div><span class="micro-label">CHAMPION</span>${playerLink(x.winner)}${x.winner_to_par!==null&&x.winner_to_par!==undefined?` <b>${toPar(x.winner_to_par)}</b>`:''}</div></div>`:''}<span class="coverage-tag">${e(coverageLabel(x.coverage))}</span></article>`;
}
function playerCard(p,{rank}={}){
 const s=p.scoring;
 return `<article class="player-card" data-division="${e(p.division)}" data-country="${e(p.country_code||'')}" data-name="${e(p.name.toLowerCase())}">${portrait(p,{size:120,cls:'card-portrait'})}<div class="player-card-body">${rank?`<span class="rank-chip">${rank}</span>`:''}<h3>${playerLink(p)}</h3><p>${e([p.country,division(p.division)].filter(Boolean).join(' · '))}</p><dl class="mini-stats"><div><dt>Wins</dt><dd>${e(p.wins_observed)}</dd></div><div><dt>Majors</dt><dd>${e(p.major_wins)}</dd></div><div><dt>Events</dt><dd>${e(p.events_observed)}</dd></div></dl>${s&&s.percentile!==null?`<div class="mini-bar" title="Scoring vs field percentile"><span style="--w:${s.percentile}%"></span><b>${s.percentile}<small>th pct scoring</small></b></div>`:''}${p.last_event?`<p class="last-event">Latest: ${a('/tournament/'+p.last_event.slug,p.last_event.name)} · ${e(pos(p.last_event))}</p>`:''}</div></article>`;
}
function courseCard(c){return `<article class="course-card">${courseImage(c,{caption:false,cls:'course-card-photo'})}<div class="course-card-body"><h3>${a('/course/'+c.slug,c.name)}</h3><p>${e([c.locality,c.country].filter(Boolean).join(' · ')||'Location unavailable')}</p><p class="micro">${e(c.editions_hosted)} championship editions${c.first_year?` · ${e(c.first_year)}–${e(c.last_year)}`:''}${c.majors_hosted?` · ${e(c.majors_hosted)} majors`:''}</p></div></article>`;}
function leaderboard(rows,{limit=null,rounds=4,par=null,caption='',showVs=false}={}){
 const list=limit?rows.slice(0,limit):rows;const n=Math.max(rounds,...list.map(r=>r.rounds.length),0);
 return `<div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable table"><table class="board"><caption>${e(caption)}</caption><thead><tr><th scope="col">Pos</th><th scope="col">Player</th>${Array.from({length:n},(_,i)=>`<th scope="col" class="num">R${i+1}</th>`).join('')}<th scope="col" class="num">Total</th><th scope="col" class="num">To par</th></tr></thead><tbody>${list.map(r=>`<tr class="${r.winner?'is-winner':''} status-${e(r.status)}"><td>${e(pos(r))}</td><td class="board-player">${r.player?`${portrait(r.player,{size:32,cls:'row-portrait'})}${playerLink(r.player)}${r.player.country?`<small>${e(r.player.country)}</small>`:''}`:'Identity under review'}</td>${Array.from({length:n},(_,i)=>{const c=r.rounds.find(x=>x.round===i+1);return `<td class="num">${c?`${e(c.strokes)}${showVs&&c.vs_field!==null?`<small class="${c.vs_field>0?'good':'bad'}">${c.vs_field>0?'+':''}${e(c.vs_field)}</small>`:''}`:''}</td>`;}).join('')}<td class="num">${e(r.strokes??'')}</td><td class="num"><b>${r.status==='finished'?toPar(r.to_par):''}</b></td></tr>`).join('')}</tbody></table></div>`;
}
function scorecards(d){
 const withHoles=d.leaderboard.filter(r=>r.holes?.length);if(!withHoles.length||!d.layout?.holes?.length)return '';
 const H=d.layout.holes;
 return section('HOLE BY HOLE','Final-round scorecards',`<p class="lede-small">Hole scores derived from the source article’s published final-round scorecard; each card is accepted only when its strokes reproduce the player’s published round score exactly.</p><div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable table"><table class="scorecard"><thead><tr><th scope="col">Hole</th>${H.map(h=>`<th scope="col">${h.hole}</th>`).join('')}<th scope="col">Tot</th></tr><tr class="par-row"><th scope="row">Par</th>${H.map(h=>`<td>${h.par}</td>`).join('')}<td>${H.reduce((s,h)=>s+h.par,0)}</td></tr>${H.some(h=>h.yards)?`<tr class="yard-row"><th scope="row">Yds</th>${H.map(h=>`<td>${e(h.yards??'')}</td>`).join('')}<td>${e(d.layout.yardage??'')}</td></tr>`:''}</thead><tbody>${withHoles.map(r=>{const card=r.holes.at(-1);return `<tr><th scope="row">${playerLink(r.player)}</th>${card.scores.map(s=>`<td class="hs hs-${s.to_par<=-2?'eagle':s.to_par===-1?'birdie':s.to_par===0?'par':s.to_par===1?'bogey':'double'}">${e(s.strokes)}</td>`).join('')}<td><b>${card.scores.reduce((x,s)=>x+s.strokes,0)}</b></td></tr>`;}).join('')}</tbody></table></div><p class="legend"><span class="hs-eagle">Eagle or better</span><span class="hs-birdie">Birdie</span><span class="hs-par">Par</span><span class="hs-bogey">Bogey</span><span class="hs-double">Double+</span></p>`);
}
function fingerprint(fp,{compact=false}={}){
 if(!fp)return `<p class="empty-note">No full-field results in coverage yet, so no DNA percentiles are published for this player.</p>`;
 if(!fp.dimensions.some(d=>d.percentile!==null)){const r=fp.dimensions.find(d=>d.basis==='rounds')?.sample||0,s=fp.dimensions.find(d=>d.basis==='starts')?.sample||0;return `<p class="empty-note">DNA percentiles are withheld: ${r} full-field round${r===1?'':'s'} and ${s} full-field start${s===1?'':'s'} observed (${e(fp.window)}), below the Limited confidence floor of 8 rounds / 3 starts.</p>`;}
 return `<div class="dna-print${compact?' compact':''}" role="list">${fp.dimensions.map(d=>`<div class="dna-row" role="listitem"><span class="dna-label">${e(DIM_LABELS[d.code]||d.code)}</span><span class="dna-bar" aria-hidden="true"><i style="--w:${d.percentile??0}%" class="${d.percentile===null?'na':d.percentile>=75?'hi':d.percentile<=25?'lo':''}"></i></span><span class="dna-pct">${d.percentile===null?'—':d.percentile}<small>${d.percentile===null?'':'th'}</small></span>${compact?'':conf(d.confidence)}${compact?'':`<span class="dna-n">n=${e(d.sample)} ${e(d.basis)}</span>`}</div>`).join('')}</div><p class="dna-foot">${e(fp.window)} · ${e(fp.cohort)} · percentiles withheld below Limited confidence (rounds ≥ 8, starts ≥ 3) and cohorts under 10 players.</p>`;
}
const strengths=fp=>{if(!fp)return '';const ok=fp.dimensions.filter(d=>d.percentile!==null&&['HIGH','MEDIUM'].includes(d.confidence));const hi=ok.filter(d=>d.percentile>=75).sort((a,b)=>b.percentile-a.percentile),lo=ok.filter(d=>d.percentile<=25).sort((a,b)=>a.percentile-b.percentile);
 return `<div class="strengths"><div><h3>Above cohort</h3>${hi.length?`<ul>${hi.map(d=>`<li>${e(DIM_LABELS[d.code])} <b>${d.percentile}th</b></li>`).join('')}</ul>`:'<p>No dimension at or above the 75th percentile with medium or high confidence.</p>'}</div><div><h3>Below cohort</h3>${lo.length?`<ul>${lo.map(d=>`<li>${e(DIM_LABELS[d.code])} <b>${d.percentile}th</b></li>`).join('')}</ul>`:'<p>No dimension at or below the 25th percentile with medium or high confidence.</p>'}</div></div>`;};
const premiumLock=(title,body,module)=>`<div class="premium-lock" data-premium="${e(module)}"><span class="lock-mark" aria-hidden="true">◆</span><div><h3>${e(title)}</h3><p>${e(body)}</p><p class="premium-status" role="status">Included with PropBetEdge All Access.</p>${go('/all-access','All Access details','button button-gold')}</div></div>`;
const held=ix=>`<details class="held-dims"><summary>${ix.held_dimensions.length} dimensions not measured yet</summary><ul>${ix.held_dimensions.map(h=>`<li><b>${e(h.label)}</b> — ${e(h.reason)}</li>`).join('')}</ul></details>`;
// ---------------- pages
export function home(ix){
 const lead=ix.current[0]||ix.recent[0]||ix.editions[0];
 const men=ix.players.filter(p=>p.division==='men'&&p.scoring?.confidence==='HIGH').sort((a,b)=>b.scoring.percentile-a.scoring.percentile).slice(0,4),women=ix.players.filter(p=>p.division==='women'&&p.scoring?.confidence==='HIGH').sort((a,b)=>b.scoring.percentile-a.scoring.percentile).slice(0,4);
 const nextBy=div=>ix.current.find(x=>x.division===div)||ix.upcoming.find(x=>x.division===div);const lastBy=div=>ix.recent.find(x=>x.division===div);
 const latestMajor=div=>ix.editions.find(x=>x.is_major&&x.division===div&&x.winner);
 return `<section class="home-hero data-home-hero"><div class="home-hero-image"><picture><source type="image/avif" srcset="/media/golf-sunrise-1280.avif"><img src="/media/golf-sunrise-1280.webp" width="1920" height="960" alt="" fetchpriority="high"></picture></div><div class="home-hero-shade"></div><div class="home-hero-content"><p class="eyebrow">${lead.status==='in_progress'?'THIS WEEK':'LATEST RESULT'} / ${e(tourLabel(lead).toUpperCase())}</p><h1>${e(lead.name)}</h1><p>${e(dates(lead))}${lead.course?' · '+e(lead.course.name):lead.location?' · '+e(lead.location):''}</p>${lead.winner?`<div class="hero-winner">${portrait(lead.winner,{size:72,cls:'hero-portrait',eager:true})}<div><span>Champion</span><a href="/player/${e(lead.winner.slug)}">${e(lead.winner.name)}</a>${lead.winner_to_par!==null&&lead.winner_to_par!==undefined?`<b>${toPar(lead.winner_to_par)}</b>`:''}</div></div>`:`<p>${e(statusLabel(lead.status))} · live scoring is not connected</p>`}<div class="hero-ctas">${go('/tournament/'+lead.slug,'Tournament page','button button-gold')}${go('/pbecast?tournament='+lead.slug,'Open in PBEcast','button button-glass')}</div></div><div class="hero-caption"><span>${e(ix.coverage.full_field_editions)} FULL-FIELD LEADERBOARDS · ${e(ix.coverage.men_majors+ix.coverage.women_majors)} MAJOR EDITIONS</span><span>BACKGROUND: EDITORIAL PHOTOGRAPH · CC0 · NOT THE VENUE</span></div></section>${freshness(ix)}<div class="page-body data-body">`
 +section('TODAY IN GOLF','The week across both tours.',`<div class="today-grid">${['men','women'].map(div=>{const n=nextBy(div),l=lastBy(div);return `<div class="today-col"><h3>${div==='men'?'PGA TOUR':'LPGA Tour'}</h3>${n?`<div class="today-item"><span class="micro-label">${n.status==='in_progress'?'IN PROGRESS (SCHEDULE)':'NEXT ON THE SCHEDULE'}</span>${edLink(n)}<p>${e(dates(n))}${n.location?' · '+e(n.location):''}</p></div>`:''}${l?`<div class="today-item"><span class="micro-label">LATEST CHAMPION</span>${edLink(l)}<p>${l.winner?playerLink(l.winner):''} ${l.winner_to_par!==null&&l.winner_to_par!==undefined?toPar(l.winner_to_par):''} · ${e(fmtDate(l.ends_on))}</p></div>`:''}</div>`;}).join('')}</div>${go('/today','Full schedule and results')}`)
 +section('RECENT RESULTS','Champions, week by week.',`<div class="event-grid">${ix.recent.slice(0,8).map(x=>eventCard(x)).join('')}</div>${go('/tournaments','All tournaments')}`)
 +section('PLAYER INTELLIGENCE','Who is outscoring the field.',`<p class="lede-small">Highest scoring-vs-field percentile over the last 24 months, high-confidence samples only. Men and women are separate cohorts.</p><div class="split"><div><h3 class="split-title">Men</h3><div class="player-grid">${men.map(p=>playerCard(p)).join('')}</div></div><div><h3 class="split-title">Women</h3><div class="player-grid">${women.map(p=>playerCard(p)).join('')}</div></div></div>${go('/players','Player directory')}`)
 +section('MAJORS','The championships that define careers.',`<div class="majors-latest">${['men','women'].map(div=>`<div><h3 class="split-title">${div==='men'?'Men’s majors':'Women’s majors'}</h3><ul class="major-list">${SERIES.filter(s=>s[2]===div&&s[0]!=='players').map(s=>{const x=ix.editions.find(y=>y.series_key===s[0]&&y.winner);return `<li><a href="/majors/${s[0]}">${e(s[1])}</a>${x?`<span>${e(x.year)} · ${playerLink(x.winner)}</span>`:''}</li>`;}).join('')}</ul></div>`).join('')}</div>${go('/majors','Major championship history')}`)
 +section('COURSE INTELLIGENCE','Where championships are decided.',`<div class="course-grid">${ix.courses.filter(c=>c.photo?.derivatives).slice(0,6).concat(ix.courses.filter(c=>!c.photo?.derivatives)).slice(0,6).map(courseCard).join('')}</div>${go('/courses','Course directory')}`)
 +section('MATCHUPS','Compare any two golfers.',`<div class="matchup-strip">${(ix.featured_matchups||[]).slice(0,4).map(m=>`<a class="matchup-chip" href="/matchups/${e(m.a.slug)}/${e(m.b.slug)}">${portrait(m.a,{size:40,cls:'mini-portrait'})}<span>${e(m.a.name)} <i>vs</i> ${e(m.b.name)}</span>${portrait(m.b,{size:40,cls:'mini-portrait'})}</a>`).join('')}</div>${go('/matchups','Matchup finder')}`)
 +`<section class="all-access-ribbon"><div><h2>All Access opens the full DNA.</h2><p>Raw values, cohort detail, Course Fit components and field intelligence are included with PropBetEdge All Access.</p></div>${go('/all-access','Membership details','button button-light')}</section>${attribution}</div>`;
}
export function today(ix){
 return heading('THE DAILY DESK','Today in golf.','Schedule status from the published PGA TOUR and LPGA season schedules, plus the latest final results. Live scoring is not connected.')+freshness(ix)+`<div class="page-body data-body">`+
 (ix.current.length?section('THIS WEEK','In progress by schedule',`<div class="event-grid">${ix.current.map(x=>eventCard(x,{big:true})).join('')}</div><p class="lede-small">“In progress” reflects the published schedule dates only; no live leaderboard is shown.</p>`):'')+
 section('UPCOMING','Next on the schedule',`<div class="event-grid">${ix.upcoming.map(x=>eventCard(x)).join('')||'<p class="empty-note">No upcoming events are listed in the current season schedules.</p>'}</div>`)+
 section('RESULTS','Latest champions',`<div class="event-grid">${ix.recent.map(x=>eventCard(x)).join('')}</div>`)+attribution+'</div>';
}
export function live(ix){
 const last=ix.recent.find(x=>x.coverage==='full_field')||ix.recent[0];
 return heading('LIVE','Live scoring is not connected.','No approved real-time scoring source exists for golf yet: PGA TOUR access is blocked (403) and other providers require licences. PropBetEdge never infers a live leaderboard from schedules or history.')+`<div class="page-body data-body">`+
 (ix.current.length?section('BY SCHEDULE','Events in their scheduled window',`<div class="event-grid">${ix.current.map(x=>eventCard(x)).join('')}</div>`):'')+
 (last?section('MOST RECENT FINAL','The latest completed leaderboard',`<div class="event-grid">${eventCard(last,{big:true})}</div>${go('/pbecast?tournament='+last.slug,'Replay it in PBEcast')}`):'')+'</div>';
}
export function tournaments(ix){
 const years=[...new Set(ix.editions.map(x=>x.year))].sort((a,b)=>b-a);
 return heading('TOURNAMENTS','Every edition in coverage.',`${ix.editions.length.toLocaleString('en-US')} editions: PGA TOUR and LPGA seasons 2024–2026, every edition of the nine majors and The Players.`)+freshness(ix)+`<div class="page-body data-body"><div class="filters" role="group" aria-label="Filter tournaments"><label>Division <select data-filter="division"><option value="">All</option><option value="men">Men</option><option value="women">Women</option></select></label><label>Type <select data-filter="major"><option value="">All events</option><option value="true">Majors only</option></select></label><label>Season <select data-filter="year"><option value="">All seasons</option>${years.map(y=>`<option value="${y}" ${y===years[0]?'':''}>${y}</option>`).join('')}</select></label><span class="filter-count" role="status" data-filter-count>${ix.editions.length} editions</span></div><div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable table"><table class="index-table" data-filter-table><caption>Tournament editions, most recent first</caption><thead><tr><th scope="col">Season</th><th scope="col">Event</th><th scope="col">Tour</th><th scope="col">Course</th><th scope="col">Champion</th><th scope="col">Coverage</th></tr></thead><tbody>${ix.editions.map(x=>`<tr data-division="${e(x.division)}" data-major="${x.is_major}" data-year="${x.year}"><td>${x.year}</td><td>${edLink(x)}</td><td>${e(tourLabel(x))}</td><td>${x.course?a('/course/'+x.course.slug,x.course.name):e(x.location||'—')}</td><td>${x.winner?playerLink(x.winner):e(statusLabel(x.status))}</td><td>${e(coverageLabel(x.coverage))}</td></tr>`).join('')}</tbody></table></div>${attribution}</div>`;
}
export function edition(d,ix){
 const winner=d.leaderboard.find(r=>r.winner),fullBoard=d.leaderboard.length>0;
 const tour=d.tours?.length?d.tours.join(' · '):d.is_major?(d.division==='women'?'Women’s major':'Men’s major'):division(d.division);
 const info=`<dl class="fact-row"><div><dt>Status</dt><dd>${e(statusLabel(d.status))}</dd></div><div><dt>Dates</dt><dd>${e(dates(d))}</dd></div><div><dt>Course</dt><dd>${d.course?a('/course/'+d.course.slug,d.course.name):e(d.schedule?.location||'—')}</dd></div><div><dt>Par / Yards</dt><dd>${e(d.par??'—')} / ${e(d.layout?.yardage?d.layout.yardage.toLocaleString('en-US'):'—')}</dd></div>${d.results_source?.field_size?`<div><dt>Field</dt><dd>${e(d.results_source.field_size)}${d.results_source.made_cut?` · ${e(d.results_source.made_cut)} made cut`:''}</dd></div>`:''}${d.results_source?.cut?.score_to_par!==undefined&&d.results_source?.cut?`<div><dt>Cut</dt><dd>${e(d.results_source.cut.strokes)} (${toPar(d.results_source.cut.score_to_par)})</dd></div>`:''}${d.results_source?.playoff?'<div><dt>Finish</dt><dd>Playoff</dd></div>':''}</dl>`;
 const hero=`<section class="event-hero"><div class="event-hero-main">${kicker((tour+' · '+d.year).toUpperCase())}<h1>${e(d.name)}</h1>${info}<div class="hero-ctas">${go('/pbecast?tournament='+d.slug,'Open in PBEcast','button button-gold')}${d.tournament&&d.series_key?go('/majors/'+d.series_key,'Championship history','button button-ghost'):''}</div></div>${winner?`<aside class="champion-card">${portrait(winner.player,{size:220,cls:'champion-portrait',eager:true,caption:true})}<span class="micro-label">CHAMPION</span><h2>${playerLink(winner.player)}</h2><p>${e(winner.strokes??'')} ${winner.to_par!==null?'('+toPar(winner.to_par)+')':''}${winner.margin===0?' · won in a playoff':winner.margin?` · won by ${e(winner.margin)}`:''}</p></aside>`:''}</section>`;
 const cov=`<p class="coverage-line">${pill(coverageLabel(d.coverage))} ${d.results_source?`${e(d.results_source.rows_stored)} of ${e(d.results_source.rows_listed)} published rows linked to verified identities${d.results_source.rows_with_inconsistent_scores?` · ${e(d.results_source.rows_with_inconsistent_scores)} rows held because published rounds do not sum to the total`:''}`:'Champion from Wikidata; no leaderboard in coverage.'}</p>`;
 const timeline=d.timeline?.length?section('ROUND BY ROUND','Who led after each round',`<ol class="timeline">${d.timeline.map(t=>`<li><span class="tl-round">R${t.after_round}</span><div><b>${t.leaders.map(l=>playerLink(l)).join(', ')}</b><p>${e(t.total)} (${toPar(t.to_par)}) · field average ${e(t.field_average)} over ${e(t.players_in_round)} players</p></div></li>`).join('')}</ol>`):'';
 const field=d.field?section('FIELD INTELLIGENCE','Pre-tournament context',`<p class="lede-small">${e(d.field.time_safe)}. ${e(d.field.players)} players in the published field.${d.field.first_observed_appearances!==null?` ${e(d.field.first_observed_appearances)} first observed appearances at this tournament since 2000.`:''}</p>${d.field.major_champions.length?`<h3 class="split-title">Major champions in the field</h3><div class="chip-row">${d.field.major_champions.map(r=>`<a class="person-chip" href="/player/${e(r.slug)}">${portrait(r,{size:36,cls:'mini-portrait'})}<span>${e(r.name)}<small>${r.major_wins_before} major${r.major_wins_before>1?'s':''} before · finished ${r.finish?(r.finish):r.status}</small></span></a>`).join('')}</div>`:''}${premiumLock('Recent-form and course-history leaders','Field members ranked by scoring vs field in the 12 months before this event and at this course, with samples.','field')}`):'';
 const course=d.layout?.holes?.length?section('COURSE SETUP',d.layout.label,`<div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable table"><table class="holes"><thead><tr><th scope="col">Hole</th>${d.layout.holes.map(h=>`<th scope="col">${h.hole}</th>`).join('')}</tr></thead><tbody><tr><th scope="row">Par</th>${d.layout.holes.map(h=>`<td>${h.par}</td>`).join('')}</tr><tr><th scope="row">Yards</th>${d.layout.holes.map(h=>`<td>${e(h.yards??'—')}</td>`).join('')}</tr></tbody></table></div><p class="lede-small">Setup as published for this edition. Hole routing and hazards are not sourced and never drawn.</p>`):'';
 const history=d.past_editions?.length?section('CHAMPIONSHIP HISTORY','Previous editions',`<div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable table"><table class="index-table"><thead><tr><th scope="col">Year</th><th scope="col">Champion</th><th scope="col">To par</th></tr></thead><tbody>${d.past_editions.slice(0,25).map(x=>`<tr><td>${a('/tournament/'+x.slug,String(x.year))}</td><td>${x.winner?playerLink(x.winner):'—'}</td><td>${toPar(x.to_par)}</td></tr>`).join('')}</tbody></table></div>`):'';
 return hero+`<div class="page-body data-body">${cov}`+(fullBoard&&!['winner_only','schedule_only'].includes(d.coverage)?section('LEADERBOARD',d.coverage==='full_field'?'Final leaderboard':'Final leaderboard (published rows)',leaderboard(d.leaderboard,{rounds:d.results_source?.rounds_played||4,caption:coverageLabel(d.coverage)+'. Small figures: strokes better (+) or worse (−) than that round’s field average.',showVs:d.coverage==='full_field'})):'')+timeline+scorecards(d)+field+course+history+attribution+'</div>';
}
export function players(ix){
 const top=ix.players.slice(0,120);const countries=[...new Map(ix.players.filter(p=>p.country_code).map(p=>[p.country_code,p.country])).entries()].sort((a,b)=>String(a[1]).localeCompare(String(b[1])));
 return heading('PLAYERS','Beyond the leaderboard.',`${ix.players.length.toLocaleString('en-US')} golfers with observed results. Totals are observed in PropBetEdge coverage, not career totals.`)+freshness(ix)+`<div class="page-body data-body"><form class="filters" role="search" data-player-filters onsubmit="return false"><label>Search <input type="search" name="q" placeholder="Player name" autocomplete="off" data-player-search></label><label>Division <select name="division"><option value="">All</option><option value="men">Men</option><option value="women">Women</option></select></label><label>Country <select name="country"><option value="">All countries</option>${countries.map(([c,n])=>`<option value="${e(c)}">${e(n||c)}</option>`).join('')}</select></label><label>Sort <select name="sort"><option value="events_observed">Most events</option><option value="wins_observed">Wins</option><option value="major_wins">Major wins</option><option value="scoring">Scoring vs field (24m)</option><option value="form">Recent form</option><option value="name">Name</option></select></label><span class="filter-count" role="status" data-filter-count>Showing ${top.length} of ${ix.players.length}</span></form><div class="player-grid" data-player-grid>${top.map(p=>playerCard(p)).join('')}</div><p class="lede-small">Sorting by scoring or form only includes players with a published percentile (sample at Limited confidence or better).</p></div>`;
}
export function player(d,ix){
 const s=d.summary,fp=d.dna_public;
 const majors=d.results.filter(r=>r.edition.is_major);
 const hero=`<section class="player-hero">${portrait(d,{size:320,cls:'hero-photo',eager:true,caption:true})}<div class="player-hero-main">${kicker([division(d.division),d.country].filter(Boolean).join(' · ').toUpperCase())}<h1>${e(d.name)}</h1><dl class="fact-row"><div><dt>Age</dt><dd>${e(d.age??'—')}</dd></div><div><dt>Born</dt><dd>${e(d.birth_date?fmtDate(d.birth_date):d.birth_year||'—')}</dd></div><div><dt>Events observed</dt><dd>${e(s.events_observed)}</dd></div><div><dt>Wins observed</dt><dd>${e(s.wins_observed)}</dd></div><div><dt>Major wins</dt><dd>${e(s.major_wins)}</dd></div><div><dt>Latest</dt><dd>${s.last_event?a('/tournament/'+s.last_event.slug,s.last_event.name)+' · '+e(pos(s.last_event)):'—'}</dd></div></dl><div class="hero-dna"><span class="micro-label">PLAYER DNA FINGERPRINT</span>${fingerprint(fp,{compact:true})}</div></div></section>`;
 const seasons=d.seasons.length?section('SEASON STATISTICS','Season by season',`<div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable table"><table class="index-table"><caption>Observed in PropBetEdge coverage. Scoring vs field uses full-field leaderboards only.</caption><thead><tr><th scope="col">Season</th><th scope="col" class="num">Events</th><th scope="col" class="num">Full-field starts</th><th scope="col" class="num">Wins</th><th scope="col" class="num">Top 10</th><th scope="col" class="num">Cuts made</th><th scope="col" class="num">Rounds</th><th scope="col" class="num">Vs field</th><th scope="col" class="num">Avg to par</th></tr></thead><tbody>${d.seasons.map(x=>`<tr><td>${x.season}</td><td class="num">${x.events_observed}</td><td class="num">${x.full_field_starts}</td><td class="num">${x.wins}</td><td class="num">${x.top10}</td><td class="num">${x.full_field_starts?x.cuts_made+'/'+x.full_field_starts:'—'}</td><td class="num">${x.rounds||'—'}</td><td class="num">${x.scoring_vs_field===null?'—':(x.scoring_vs_field>0?'+':'')+x.scoring_vs_field}</td><td class="num">${x.avg_to_par_per_round===null?'—':toPar(Math.round(x.avg_to_par_per_round*100)/100)}</td></tr>`).join('')}</tbody></table></div>`):'';
 const results=(rows,cap)=>`<div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable table"><table class="index-table"><caption>${e(cap)}</caption><thead><tr><th scope="col">Event</th><th scope="col">Finish</th><th scope="col" class="num">Rounds</th><th scope="col" class="num">To par</th><th scope="col">Coverage</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${a('/tournament/'+r.edition.slug,r.edition.name)}</td><td>${e(pos(r))}${r.winner?' 🏆':''}</td><td class="num">${r.rounds.map(c=>c.strokes).join('-')||'—'}</td><td class="num">${r.status==='finished'?toPar(r.to_par):'—'}</td><td>${e(coverageLabel(r.edition.coverage))}</td></tr>`).join('')}</tbody></table></div>`;
 const ch=d.course_history.filter(h=>h.appearances_observed>0).slice(0,12);
 return hero+`<div class="page-body data-body">`+
  section('PLAYER DNA','Results DNA',`${fingerprint(fp)}${strengths(fp)}${premiumLock('Full DNA values and both windows','Raw values, cohort sizes, 24-month and all-observed windows, and per-dimension definitions for every metric.','player-dna')}${held(ix)}`)+
  section('RECENT FORM','Latest events',results(d.recent,'Most recent observed events'))+seasons+
  (majors.length?section('MAJORS','Major championship record',`<div class="stat-row">${stat('Major wins',s.major_wins,'all recorded editions')}${stat('Appearances observed',s.major_appearances_observed)}${stat('Top 10s',s.major_top10,'2000–present leaderboards')}${stat('Best finish',s.best_major_finish?(s.best_major_finish===1?'Won':s.best_major_finish):'—')}</div>${results(majors,'Major championships in coverage')}`):'')+
  (ch.length?section('COURSE HISTORY','Where they have played',`<div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable table"><table class="index-table"><thead><tr><th scope="col">Course</th><th scope="col" class="num">Appearances</th><th scope="col" class="num">Best</th><th scope="col" class="num">Top 10</th><th scope="col" class="num">Cuts</th><th scope="col" class="num">Rounds</th><th scope="col" class="num">Vs field</th></tr></thead><tbody>${ch.map(h=>`<tr><td>${a('/course/'+h.course.slug,h.course.name)}</td><td class="num">${h.appearances_observed}</td><td class="num">${h.best_finish?(h.best_finish===1?'Won':h.best_finish):'—'}</td><td class="num">${h.top10}</td><td class="num">${h.full_field_starts?h.cuts_made+'/'+h.full_field_starts:'—'}</td><td class="num">${h.rounds||'—'}</td><td class="num">${h.scoring_vs_field===null?'—':(h.scoring_vs_field>0?'+':'')+h.scoring_vs_field}</td></tr>`).join('')}</tbody></table></div>`):'')+
  section('MATCHUPS','Compare',`<div class="matchup-strip">${ix.players.filter(p=>p.slug!==d.slug&&p.division===d.division).slice(0,6).map(p=>{const [x,y]=[d.slug,p.slug].sort();return `<a class="matchup-chip" href="/matchups/${e(x)}/${e(y)}">${portrait(p,{size:36,cls:'mini-portrait'})}<span>vs ${e(p.name)}</span></a>`;}).join('')}</div>${go('/matchups?a='+d.slug,'Build a matchup')}`)+
  section('ALL RESULTS','Event history',results(d.results,'All observed events'))+
  `<details class="data-proof"><summary>Identity, sources and coverage</summary><p>Identity: Wikidata ${e(d.wikidata_id)} (distinct human classified as a golfer; never merged by name).${Object.keys(d.external_ids||{}).length?' Crosswalk identifiers recorded: '+e(Object.keys(d.external_ids).join(', '))+'.':''}</p><p>“Observed” totals cover events in PropBetEdge coverage: every edition of the nine majors and The Players (winners), leaderboards from 2000, and PGA TOUR/LPGA seasons 2024–2026.</p></details>${attribution}</div>`;
}
export function courses(ix){
 return heading('COURSES','Every course has a character.',`${ix.courses.length} championship venues with tournament history, published setups and scoring.`)+freshness(ix)+`<div class="page-body data-body"><div class="course-grid">${ix.courses.map(courseCard).join('')}</div>${attribution}</div>`;
}
export function course(d,ix){
 const latest=d.dna?.layout_versions?.at(0),dims=d.dna?.dimensions||[];
 const hero=`<section class="course-hero">${courseImage(d,{cls:'course-hero-photo',eager:true})}<div class="course-hero-main">${kicker([d.locality,d.country].filter(Boolean).join(' · ').toUpperCase()||'COURSE')}<h1>${e(d.name)}</h1><dl class="fact-row"><div><dt>Editions hosted</dt><dd>${e(d.editions.length)}</dd></div><div><dt>Majors</dt><dd>${e(d.editions.filter(x=>x.is_major).length)}</dd></div><div><dt>Latest par</dt><dd>${e(d.editions.find(x=>x.par)?.par??'—')}</dd></div><div><dt>Latest yardage</dt><dd>${e(d.editions.find(x=>x.yardage)?.yardage?.toLocaleString('en-US')??'—')}</dd></div>${d.opened_year?`<div><dt>Opened</dt><dd>${e(d.opened_year)}</dd></div>`:''}${d.architects?.length?`<div><dt>Architect</dt><dd>${e(d.architects.join(', '))}</dd></div>`:''}</dl></div></section>`;
 const dna=d.dna&&d.dna.full_field_editions?section('COURSE DNA','How this course plays',`<p class="lede-small">${e(d.dna.full_field_editions)} full-field editions (${e(d.dna.edition_range?.join('–'))}), ${e(d.dna.division==='women'?'women’s':'men’s')} cohort. ${conf(d.dna.confidence)}</p><div class="course-dna">${dims.map(x=>`<div class="cdna"><span class="micro-label">${e(x.label)}</span><b>${x.value===null?'—':e(x.code==='difficulty'||x.code==='winning_score'||x.code==='cut_line'?toPar(x.value):x.value)}</b><small>${e(x.unit)}</small>${x.percentile!==null&&x.percentile!==undefined?`<span class="dna-bar" aria-hidden="true"><i style="--w:${x.percentile}%"></i></span><small>${x.percentile}th percentile of ${e(x.cohort_size)} courses</small>`:''}<small>n=${e(x.sample)} · ${e(x.confidence)}</small></div>`).join('')}</div><details class="held-dims"><summary>Not measured</summary><ul>${d.dna.held.map(h=>`<li><b>${e(h.label)}</b> — ${e(h.reason)}</li>`).join('')}</ul></details>`):section('COURSE DNA','How this course plays',`<p class="empty-note">Course DNA needs at least two full-field editions at this venue; ${e(d.editions.length)} edition${d.editions.length===1?' is':'s are'} in coverage, and none has a full field yet.</p>`);
 const layouts=d.dna?.layout_versions?.length?section('LAYOUT VERSIONS','Published championship setups',`<div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable table"><table class="index-table"><caption>Each edition’s setup is a separate layout version; years are never mixed.</caption><thead><tr><th scope="col">Edition</th><th scope="col" class="num">Par</th><th scope="col" class="num">Yards</th><th scope="col" class="num">Hole table</th></tr></thead><tbody>${d.dna.layout_versions.map(l=>`<tr><td>${a('/tournament/'+l.edition,l.label)}</td><td class="num">${e(l.par??'—')}</td><td class="num">${e(l.yardage?.toLocaleString('en-US')??'—')}</td><td class="num">${l.holes?'18 holes':'—'}</td></tr>`).join('')}</tbody></table></div>`):'';
 const holes=d.contender_hole_scoring?section('HOLES','Hole by hole',`<p class="lede-small">${e(d.contender_hole_scoring.year)} setup. Scoring column: ${e(d.contender_hole_scoring.basis)}.</p><div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable table"><table class="index-table"><thead><tr><th scope="col">Hole</th><th scope="col" class="num">Par</th><th scope="col" class="num">Yards</th><th scope="col" class="num">Contenders’ avg to par</th><th scope="col" class="num">Cards</th></tr></thead><tbody>${d.contender_hole_scoring.holes.map(h=>`<tr><td>${h.hole}</td><td class="num">${h.par}</td><td class="num">${e(h.yards??'—')}</td><td class="num">${h.avg_to_par===null?'—':(h.avg_to_par>0?'+':'')+h.avg_to_par}</td><td class="num">${h.sample}</td></tr>`).join('')}</tbody></table></div>`):'';
 const hist=section('TOURNAMENT HISTORY','Champions here',`<div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable table"><table class="index-table"><thead><tr><th scope="col">Edition</th><th scope="col">Champion</th><th scope="col" class="num">To par</th><th scope="col">Coverage</th></tr></thead><tbody>${d.editions.map(x=>`<tr><td>${a('/tournament/'+x.slug,x.name)}</td><td>${x.winner?playerLink(x.winner):'—'}</td><td class="num">${toPar(x.to_par)}</td><td>${e(coverageLabel(x.coverage))}</td></tr>`).join('')}</tbody></table></div>`);
 const ph=d.player_history?.length?section('PLAYER COURSE HISTORY','Best here against the field',`<div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable table"><table class="index-table"><caption>Players with at least 8 observed rounds here, ranked by scoring vs field.</caption><thead><tr><th scope="col">Player</th><th scope="col" class="num">Appearances</th><th scope="col" class="num">Best</th><th scope="col" class="num">Rounds</th><th scope="col" class="num">Vs field</th></tr></thead><tbody>${d.player_history.map(h=>`<tr><td class="board-player">${portrait(h,{size:32,cls:'row-portrait'})}${playerLink(h)}</td><td class="num">${h.appearances_observed}</td><td class="num">${h.best_finish?(h.best_finish===1?'Won':h.best_finish):'—'}</td><td class="num">${h.rounds}</td><td class="num">${(h.scoring_vs_field>0?'+':'')+h.scoring_vs_field}</td></tr>`).join('')}</tbody></table></div>${premiumLock('Course Fit for every player','Player DNA against this course’s profile: course history, difficult-setup and length alignment, recent form. Each component shows the player value, the course signal and both samples. No composite score.','course-fit')}`):'';
 return hero+`<div class="page-body data-body">`+dna+holes+layouts+hist+ph+`<details class="data-proof"><summary>Identity and sources</summary><p>Venue identity: Wikidata ${e(d.wikidata_id)}. ${d.latitude?`Coordinates ${e(d.latitude)}, ${e(d.longitude)}.`:''} Setups and results from edition articles on Wikipedia (CC BY-SA 4.0).</p></details>${attribution}</div>`;
}
export function majorsIndex(ix){
 return heading('MAJORS','The championships that define careers.','Every recorded edition of the four men’s majors, the five women’s majors and The Players, with champions; leaderboards from 2000.')+freshness(ix)+`<div class="page-body data-body">${['men','women'].map(div=>section(div==='men'?'MEN':'WOMEN',div==='men'?'Men’s majors':'Women’s majors',`<div class="series-grid">${ix.series.filter(s=>(s.division||SERIES.find(x=>x[0]===s.key)?.[2])===div).map(s=>`<a class="series-card" href="/majors/${e(s.key)}"><span class="micro-label">${e(s.editions)} EDITIONS${s.first_year?' · SINCE '+s.first_year:''}</span><h3>${e(seriesName(s.key))}</h3>${s.latest?.winner?`<p>${e(s.latest.year)} champion: ${e(s.latest.winner.name)}</p>`:''}</a>`).join('')}</div>`)).join('')}<p class="lede-small">Women’s major counts exclude defunct majors (Titleholders, Western Open, du Maurier Classic), which are outside current coverage.</p>${attribution}</div>`;
}
export function series(key,ix){
 const eds=ix.editions.filter(x=>x.series_key===key);if(!eds.length)return null;
 const wins=new Map();for(const x of eds)if(x.winner){const w=wins.get(x.winner.slug)||{...x.winner,n:0,years:[]};w.n++;w.years.push(x.year);wins.set(x.winner.slug,w);}
 const most=[...wins.values()].sort((a,b)=>b.n-a.n||a.name.localeCompare(b.name)).slice(0,10);
 return heading('MAJORS / '+(eds[0].division==='women'?'WOMEN':'MEN'),seriesName(key),`${eds.length} editions from ${eds.at(-1).year} to ${eds[0].year}. Champions for every edition; full leaderboards from 2000.`)+freshness(ix)+`<div class="page-body data-body">${section('MOST WINS','Multiple champions',`<div class="chip-row">${most.filter(w=>w.n>1).map(w=>`<a class="person-chip" href="/player/${e(w.slug)}">${portrait(w,{size:40,cls:'mini-portrait'})}<span>${e(w.name)}<small>${w.n} wins · ${w.years.sort().join(', ')}</small></span></a>`).join('')||'<p>No multiple champions in coverage.</p>'}</div>`)}${section('EDITIONS','Every edition',`<div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable table"><table class="index-table"><thead><tr><th scope="col">Year</th><th scope="col">Champion</th><th scope="col" class="num">To par</th><th scope="col">Course</th><th scope="col">Coverage</th></tr></thead><tbody>${eds.map(x=>`<tr><td>${a('/tournament/'+x.slug,String(x.year))}</td><td>${x.winner?playerLink(x.winner):'—'}</td><td class="num">${toPar(x.winner_to_par)}</td><td>${x.course?a('/course/'+x.course.slug,x.course.name):'—'}</td><td>${e(coverageLabel(x.coverage))}</td></tr>`).join('')}</tbody></table></div>`)}${attribution}</div>`;
}
export function matchupsIndex(ix){
 return heading('MATCHUPS','Compare any two golfers.','Side-by-side DNA, records, shared events and course history. Descriptive intelligence, not a pick: no matchup probability is published.')+`<div class="page-body data-body"><form class="matchup-finder" data-matchup-finder onsubmit="return false"><label>Player A <input type="search" name="a" list="player-options" autocomplete="off" placeholder="Search a golfer"></label><span class="vs">vs</span><label>Player B <input type="search" name="b" list="player-options" autocomplete="off" placeholder="Search a golfer"></label><button class="button button-gold" type="submit">Compare</button><p class="finder-status" role="status" data-finder-status></p></form><datalist id="player-options"></datalist>${section('FEATURED','Featured matchups',`<div class="matchup-grid">${(ix.featured_matchups||[]).map(m=>`<a class="matchup-card" href="/matchups/${e(m.a.slug)}/${e(m.b.slug)}"><span class="micro-label">${e(m.reason)}</span><div>${portrait(m.a,{size:72,cls:'mc-portrait'})}<b>vs</b>${portrait(m.b,{size:72,cls:'mc-portrait'})}</div><h3>${e(m.a.name)} <i>vs</i> ${e(m.b.name)}</h3></a>`).join('')}</div>`)}</div>`;
}
export function matchup(m){
 const A=m.a,B=m.b,row=(label,x,y,better='higher')=>{const nx=Number(x),ny=Number(y),win=Number.isFinite(nx)&&Number.isFinite(ny)&&nx!==ny?((better==='higher'?nx>ny:nx<ny)?'a':'b'):'';return `<tr><td class="num ${win==='a'?'edge':''}">${e(x??'—')}</td><th scope="row">${e(label)}</th><td class="num ${win==='b'?'edge':''}">${e(y??'—')}</td></tr>`;};
 const dna=m.dna.a&&m.dna.b?`<table class="vs-table"><caption>DNA percentiles (${e(m.dna.note)})</caption><thead><tr><th scope="col">${e(A.name)}</th><th scope="col">Dimension</th><th scope="col">${e(B.name)}</th></tr></thead><tbody>${m.dna.a.dimensions.map((d,i)=>{const o=m.dna.b.dimensions.find(x=>x.code===d.code)||{};return row(DIM_LABELS[d.code],d.percentile!==null?d.percentile+'th':null,o.percentile!==null&&o.percentile!==undefined?o.percentile+'th':null);}).join('')}</tbody></table>`:'<p class="empty-note">One or both players have no published DNA percentiles.</p>';
 const sh=m.shared;
 return `<section class="vs-hero"><div class="vs-side">${portrait(A,{size:220,cls:'vs-photo',eager:true,caption:true})}<h2>${playerLink(A)}</h2><p>${e([A.country,division(A.division)].filter(Boolean).join(' · '))}</p></div><div class="vs-mid"><span>VS</span></div><div class="vs-side">${portrait(B,{size:220,cls:'vs-photo',eager:true,caption:true})}<h2>${playerLink(B)}</h2><p>${e([B.country,division(B.division)].filter(Boolean).join(' · '))}</p></div><h1 class="sr-only">${e(A.name)} vs ${e(B.name)}</h1></section><div class="page-body data-body">`+
  section('RECORD','Side by side',`<table class="vs-table"><thead><tr><th scope="col">${e(A.name)}</th><th scope="col">Observed</th><th scope="col">${e(B.name)}</th></tr></thead><tbody>${row('Events',A.summary.events_observed,B.summary.events_observed)}${row('Wins',A.summary.wins_observed,B.summary.wins_observed)}${row('Major wins',A.summary.major_wins,B.summary.major_wins)}${row('Major top 10s',A.summary.major_top10,B.summary.major_top10)}${row('Best major finish',A.summary.best_major_finish,B.summary.best_major_finish,'lower')}${row('Age',A.age,B.age,'none')}</tbody></table>`)+
  section('PLAYER DNA','Side-by-side DNA',dna+premiumLock('Raw values behind each percentile','Scoring vs field, consistency, form and major values with samples for both players.','matchups'))+
  section('SHARED EVENTS','Higher finish in shared events',sh.events.length?`<div class="stat-row">${stat(A.name,sh.a_higher_finish,'higher finishes')}${stat('Level / both missed',sh.level_or_both_missed)}${stat(B.name,sh.b_higher_finish,'higher finishes')}</div><p class="lede-small">${e(sh.wording)}</p><div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable table"><table class="index-table"><thead><tr><th scope="col">Event</th><th scope="col" class="num">${e(A.name)}</th><th scope="col" class="num">${e(B.name)}</th></tr></thead><tbody>${sh.events.map(x=>`<tr><td>${a('/tournament/'+x.edition.slug,x.edition.name)}</td><td class="num">${e(pos(x.a))}${x.a.to_par!==null&&x.a.status==='finished'?' ('+toPar(x.a.to_par)+')':''}</td><td class="num">${e(pos(x.b))}${x.b.to_par!==null&&x.b.status==='finished'?' ('+toPar(x.b.to_par)+')':''}</td></tr>`).join('')}</tbody></table></div>`:'<p class="empty-note">No shared events in coverage.</p>')+
  (m.common_courses.length?section('COURSE HISTORY','Courses both have played',`<div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable table"><table class="index-table"><thead><tr><th scope="col">Course</th><th scope="col" class="num">${e(A.name)} best / vs field</th><th scope="col" class="num">${e(B.name)} best / vs field</th></tr></thead><tbody>${m.common_courses.map(c=>`<tr><td>${a('/course/'+c.course.slug,c.course.name)}</td><td class="num">${e(c.a.best_finish??'—')} / ${c.a.scoring_vs_field===null?'—':e(c.a.scoring_vs_field)}</td><td class="num">${e(c.b.best_finish??'—')} / ${c.b.scoring_vs_field===null?'—':e(c.b.scoring_vs_field)}</td></tr>`).join('')}</tbody></table></div>`):'')+
  section('RECENT FORM','Last ten events',`<div class="split">${[A,B].map(p=>`<div><h3 class="split-title">${e(p.name)}</h3><ol class="form-list">${p.recent.map(r=>`<li>${a('/tournament/'+r.edition.slug,r.edition.name)} <b>${e(pos(r))}</b></li>`).join('')}</ol></div>`).join('')}</div>`)+
  `<p class="source-note">${e(m.prediction_reason)}</p></div>`;
}
export function pbecast(ix,d){
 const opts=ix.editions.filter(x=>x.coverage==='full_field'||x.coverage==='top_finishers'||x.coverage==='made_cut').slice(0,200);
 const sel=`<label class="cast-selector">Tournament <select data-cast-select>${opts.map(x=>`<option value="${e(x.slug)}" ${x.slug===d?.slug?'selected':''}>${e(x.name)}</option>`).join('')}</select></label>`;
 if(!d)return heading('PBECAST','The tournament, replayed from the record.','Archive mode: round-by-round leaders, final-round scorecards and course context from published results. Live mode activates only with an approved real-time feed.')+`<div class="page-body data-body">${sel}</div>`;
 const top=d.leaderboard.slice(0,10),cards=d.leaderboard.filter(r=>r.holes?.length);
 return `<section class="cast-head">${kicker('PBECAST / ARCHIVE MODE')}<h1>${e(d.name)}</h1><p>${e(dates(d))}${d.course?' · '+e(d.course.name):''} · ${e(statusLabel(d.status))} · ${e(coverageLabel(d.coverage))}</p>${sel}</section><div class="cast-grid"><section class="cast-panel"><h2>Leaderboard</h2>${leaderboard(top,{rounds:d.results_source?.rounds_played||4,caption:'Top of the final leaderboard'})}${go('/tournament/'+d.slug,'Full leaderboard')}</section><section class="cast-panel"><h2>Round by round</h2>${d.timeline?.length?`<ol class="timeline">${d.timeline.map(t=>`<li><span class="tl-round">R${t.after_round}</span><div><b>${t.leaders.map(l=>playerLink(l)).join(', ')}</b><p>${e(t.total)} (${toPar(t.to_par)}) · field avg ${e(t.field_average)}</p></div></li>`).join('')}</ol>`:'<p class="empty-note">Round-by-round leaders need a full-field leaderboard.</p>'}</section><section class="cast-panel cast-wide"><h2>Final-round scorecards</h2>${cards.length?cards.slice(0,6).map(r=>{const c=r.holes.at(-1);let run=0;return `<div class="cast-card"><h3>${playerLink(r.player)} <small>${e(pos(r))}</small></h3><div class="hole-strip">${c.scores.map(s=>{run+=s.to_par;return `<span class="hs hs-${s.to_par<=-2?'eagle':s.to_par===-1?'birdie':s.to_par===0?'par':s.to_par===1?'bogey':'double'}" title="Hole ${s.hole}: ${s.strokes} (${toPar(s.to_par)}), round ${toPar(run)}"><i>${s.hole}</i>${s.strokes}</span>`;}).join('')}</div></div>`;}).join(''):'<p class="empty-note">No validated hole-by-hole scorecards were published for this edition.</p>'}<p class="lede-small">Observed hole scores only. No shot locations or trajectories exist in approved sources and none are drawn.</p></section><section class="cast-panel"><h2>Course</h2>${d.course?`<p>${a('/course/'+d.course.slug,d.course.name)}</p>`:''}<p>Par ${e(d.par??'—')} · ${e(d.layout?.yardage?.toLocaleString('en-US')??'—')} yards</p></section></div>`;
}
export function search(){return heading('SEARCH','Find players, tournaments and courses.','')+`<div class="page-body data-body"><form class="filters" role="search" data-site-search onsubmit="return false"><label>Search <input type="search" name="q" autocomplete="off" placeholder="e.g. Nelly Korda, Augusta, 2019 Open" data-search-input></label></form><div data-search-results aria-live="polite"></div></div>`;}
export function rankings(ix){return heading('RANKINGS','Official rankings are not shown.','No licensed ranking source is established: OWGR terms prohibit scraping and Rolex/WWGR require written agreements. PropBetEdge does not publish an unvalidated proprietary rating.')+`<div class="page-body data-body">${section('INSTEAD','Descriptive leaders',`<p>Player DNA percentiles compare players within their own division. ${go('/players','Sort the player directory by scoring vs field')}</p>`)}</div>`;}
export function intelligence(ix){
 return heading('INTELLIGENCE','How the numbers are made.','Player DNA, Course DNA and Course Fit are descriptive, versioned and built only from observed results.')+`<div class="page-body data-body">`+
 section('PLAYER DNA',ix.methods.dna,`<div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable table"><table class="index-table"><thead><tr><th scope="col">Dimension</th><th scope="col">Unit</th><th scope="col">Definition</th></tr></thead><tbody>${ix.dimensions.map(d=>`<tr><td>${e(d.label)}</td><td>${e(d.unit)}</td><td>${e(d.definition)}</td></tr>`).join('')}</tbody></table></div><p class="lede-small">Confidence tiers: rounds — High ≥ 40, Medium ≥ 20, Limited ≥ 8; starts — High ≥ 12, Medium ≥ 6, Limited ≥ 3. Percentiles are mid-rank within one division and window, withheld below Limited or when fewer than 10 players qualify. Windows: last 24 months and all observed since 2000. Only results that ended before the as-of date are used.</p>${held(ix)}`)+
 section('COURSE DNA',ix.methods.course,'<p>Scoring difficulty, spread and under-par rate come from every round in full-field editions at the venue, compared with other courses in the same division. Winning score and cut line use published values. Each edition’s published setup is a separate layout version.</p>')+
 section('COURSE FIT',ix.methods.fit,'<p>Descriptive components only: course history, performance on comparably difficult setups, performance on comparable lengths and recent form. Each shows the player value, the course signal and both samples. There is no composite score and no win probability.</p>')+
 section('SOURCES','Where the data comes from',`<ul class="source-list">${ix.sources.map(s=>`<li><b>${e(s.name)}</b> (${e(s.licence)}): ${e(s.role)}</li>`).join('')}</ul><p class="lede-small">Not used: PGA TOUR (access barrier), OWGR (terms prohibit scraping), ESPN and LPGA websites (no reuse licence), Data Golf (paid licence decision).</p>`,{id:'sources'})+'</div>';
}
export function news(ix,stories=[]){return heading('NEWS','The game, with evidence.','Stories publish only when every number traces to a frozen fact and the editorial gates pass.')+`<div class="page-body data-body">${stories.length?`<div class="story-list">${stories.map(s=>`<article class="story" id="${e(s.slug)}"><span class="micro-label">${e(s.kicker||'GOLF')} · ${e(fmtDate(s.published_at?.slice(0,10)))}</span><h2>${e(s.headline)}</h2>${s.paragraphs?.map(p=>`<p>${e(p)}</p>`).join('')||''}<p>${go(s.edition,'Leaderboard and scorecards')} ${go(s.winner,'Champion profile')}</p><p class="source-note">${e(s.source_note||'')}</p></article>`).join('')}</div>`:'<p class="empty-note">No story has passed every publication gate yet. Held drafts are never shown.</p>'}</div>`;}
// ---------------- All Access renderers (client-side only, after server authorization)
const fmtV=(v,code)=>v===null||v===undefined?'—':['cuts','top10','contention','under_par'].includes(code)?v+'%':(v>0&&!['consistency'].includes(code)?'+':'')+v;
export function premiumDna(d){
 const w=d.dna||{};const rows=Object.keys(DIM_LABELS);
 return `<div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable table"><table class="index-table"><caption>All Access · Player DNA values (${e(w.l24m?.cohort||w.all?.cohort||'')})</caption><thead><tr><th scope="col">Dimension</th>${['l24m','all'].map(k=>w[k]?`<th scope="col" class="num">${e(w[k].window.label)}</th><th scope="col" class="num">Pct</th><th scope="col" class="num">n</th><th scope="col" class="num">Cohort</th>`:'').join('')}</tr></thead><tbody>${rows.map(code=>`<tr><td>${e(DIM_LABELS[code])}</td>${['l24m','all'].map(k=>{const m=w[k]?.metrics?.[code];return w[k]?`<td class="num">${fmtV(m?.value,code)}</td><td class="num">${m?.percentile??'—'}</td><td class="num">${e(m?.sample??0)}</td><td class="num">${e(m?.cohort_size??'—')}</td>`:'';}).join('')}</tr>`).join('')}</tbody></table></div>`;
}
export function premiumFit(d){
 return `<h3 class="split-title">All Access · Course Fit components</h3>${d.fit.slice(0,20).map(f=>`<div class="fit-card"><h4>${e(f.name)}</h4>${f.fit?`<ul>${f.fit.components.map(c=>`<li><b>${e(c.label)}</b>: player ${c.player?.value===null||c.player?.value===undefined?'—':e(c.player.value)} <small>(${e(c.player?.unit||'')}, n=${e(c.player?.sample??0)}, ${e(c.player?.confidence||'')})</small>${c.course?` · course ${e(c.course.value)} <small>(${e(c.course.unit)})</small>`:''} — ${e(c.interpretation)}</li>`).join('')}</ul><p class="lede-small">${e(f.fit.overall_reason)}</p>`:'<p>No fit components.</p>'}</div>`).join('')}`;
}
export function premiumField(d){
 const f=d.field;if(!f)return '<p class="empty-note">No field intelligence for this edition.</p>';
 const list=(rows,val,unit)=>rows.length?`<ol class="form-list">${rows.map(r=>`<li>${playerLink(r)} <b>${e((r[val]>0?'+':'')+r[val])}</b> <small>${unit}</small></li>`).join('')}</ol>`:'<p class="empty-note">Not enough prior rounds.</p>';
 return `<div class="split"><div><h3 class="split-title">Recent-form leaders</h3>${list(f.recent_form_leaders,'form','strokes vs field, prior 12 months')}</div><div><h3 class="split-title">Course-history leaders</h3>${list(f.course_history_leaders,'course_vs_field','strokes vs field at this course')}</div></div><p class="lede-small">${e(f.time_safe)}</p>`;
}
export function premiumMatchup(d){
 const A=d.a.dna?.l24m||d.a.dna?.all,B=d.b.dna?.l24m||d.b.dna?.all;
 return `<div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable table"><table class="vs-table"><caption>All Access · DNA values (${e(A?.window?.label||'')})</caption><thead><tr><th scope="col">${e(d.a.slug)}</th><th scope="col">Dimension</th><th scope="col">${e(d.b.slug)}</th></tr></thead><tbody>${Object.keys(DIM_LABELS).map(code=>`<tr><td class="num">${fmtV(A?.metrics?.[code]?.value,code)} <small>n=${e(A?.metrics?.[code]?.sample??0)}</small></td><th scope="row">${e(DIM_LABELS[code])}</th><td class="num">${fmtV(B?.metrics?.[code]?.value,code)} <small>n=${e(B?.metrics?.[code]?.sample??0)}</small></td></tr>`).join('')}</tbody></table></div>`;
}
