const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const a=(url,text,cls='text-link')=>`<a class="${cls}" href="${e(url)}">${e(text)} <span aria-hidden="true">↗</span></a>`;
const unavailable=(name,basis='The approved metadata source does not supply this information.')=>`<article class="data-unavailable"><h3>${e(name)}</h3><p>${e(basis)}</p><span class="data-label">Unavailable</span></article>`;
const division=t=>t.major_division==='women'?"Women’s major / LPGA context":"Men’s major / PGA TOUR context";
export function eventDate(t){if(t.starts_on&&t.ends_on)return `${t.starts_on} – ${t.ends_on}`;if(t.source_date&&t.date_precision===10)return t.source_date.slice(1,8)+' · month precision';return t.edition_key+' · year precision';}
const title=(eyebrow,name,description)=>`<section class="page-heading data-heading"><div><p class="eyebrow">${e(eyebrow)}</p><h1>${e(name)}</h1><p>${e(description)}</p></div></section>`;
const source=g=>`<div class="data-source" data-asof="${e(g.as_of)}"><span>Wikidata structured data · CC0</span><span>Graph checked ${e(g.as_of?.slice(0,16).replace('T',' '))} UTC</span><span>Selected records · incomplete coverage</span><span data-freshness role="status">${g.source_age_seconds>172800?'Stale capture · refresh pending':'Metadata capture available'}</span></div>`;
const proof=r=>`<details class="data-proof"><summary>Source and coverage</summary><p>Source assertion, with references retained in the immutable capture. Independent official verification is unavailable.</p><dl><dt>Source</dt><dd>${a(r.provenance?.source_url||'https://www.wikidata.org','Wikidata API capture')}</dd><dt>Captured</dt><dd>${e(r.provenance?.captured_at)}</dd><dt>Parser</dt><dd>${e(r.provenance?.parser_version)}</dd><dt>Evidence SHA-256</dt><dd class="evidence-hash">${e(r.provenance?.sha256)}</dd></dl></details>`;
const filters=()=>`<div class="data-filters" role="group" aria-label="Filter major coverage"><button data-division="all" aria-pressed="true">All majors</button><button data-division="men" aria-pressed="false">Men’s majors</button><button data-division="women" aria-pressed="false">Women’s majors</button><span class="filter-description" role="status">Showing all captured editions.</span></div>`;
const events=ts=>`<div class="data-grid">${ts.map(t=>`<article class="data-card" data-event-division="${t.major_division}"><span class="micro-label">${e(division(t))}</span><h3>${a('/tournament/'+t.slug,t.name)}</h3><p>${e(eventDate(t))}</p><p>${e(t.course?.name||'Venue unavailable')}</p><span class="data-label">${e(t.status)} · metadata</span></article>`).join('')}</div>`;
const players=ps=>`<div class="data-grid">${ps.map(p=>`<article class="data-card"><span class="player-monogram" aria-hidden="true">${e(p.full_name.split(' ').map(x=>x[0]).slice(0,2).join(''))}</span><h3>${a('/player/'+p.slug,p.full_name)}</h3><p>${e(p.country_name||p.nationality_code||'Country unavailable')}</p><span class="data-label">Sourced identity · statistical sample unavailable</span></article>`).join('')}</div>`;
const courses=cs=>`<div class="data-grid">${cs.map(c=>`<article class="data-card"><span class="micro-label">COURSE / VENUE IDENTITY</span><h3>${a('/course/'+c.slug,c.name)}</h3><p>${e([c.locality,c.country_code].filter(Boolean).join(' · ')||'Location unavailable')}</p><span class="data-label">Routing and hole data unavailable</span></article>`).join('')}</div>`;
function results(rs){return `<div class="data-table-wrap"><table class="data-table"><caption>Source-reported winners · selected editions only</caption><thead><tr><th scope="col">Edition</th><th scope="col">Winner</th><th scope="col">Score</th></tr></thead><tbody>${rs.length?rs.map(r=>`<tr><td>${a('/tournament/'+r.tournament.slug,r.tournament.name)}</td><td>${a('/player/'+r.player.slug,r.player.full_name)}</td><td>Unavailable</td></tr>`).join(''):'<tr><td colspan="3">No winner assertion captured for this record.</td></tr>'}</tbody></table></div>`;}
const section=(name,body,kicker='GOLF INTELLIGENCE')=>`<section class="data-section"><p class="eyebrow">${e(kicker)}</p><h2>${e(name)}</h2>${body}</section>`;
const intelligence=()=>section('Evidence before a score.',`<div class="data-grid">${unavailable('Player DNA','Comparable driving, approach, putting and round statistics are unavailable.')}${unavailable('Course DNA','Venue identity is available. Hole layouts and observed scoring samples are required for course dimensions.')}${unavailable('Course Fit','Player values, cohort percentiles and historical course signals require comparable samples. Overall scores remain disabled.')}</div>${a('/intelligence','Explore the methodology')}`);
export function entityRoute(path,g){const [,kind,id]=path.split('/');const key={player:'players',course:'courses',tournament:'tournaments'}[kind];const entity=key&&g?.[key]?.find(r=>r.slug===id||r.id===id);return entity?{path,label:entity.full_name||entity.name,title:entity.full_name||entity.name,description:'Sourced golf identity and selected championship history.',entity,kind}:null;}
export function productPage(path,g,selected=''){
 if(!g?.as_of)return null;
 const detail=entityRoute(path,g);
 if(path==='/'){
  const t=g.tournaments[0],winner=g.results.find(r=>r.edition_id===t?.id);
  const hero=`<section class="home-hero data-home-hero"><div class="home-hero-image"><picture><source type="image/avif" srcset="/media/golf-sunrise-1280.avif"><img src="/media/golf-sunrise-1280.webp" width="1920" height="960" alt="Golf course at sunrise; editorial photograph, not the tournament venue" fetchpriority="high"></picture></div><div class="home-hero-shade"></div><div class="home-hero-content"><p class="eyebrow">GOLF / LATEST CAPTURED MAJOR EDITION</p><h1>${e(t?.name||'Golf, in focus.')}</h1><p>${e(t?.course?.name||'Venue unavailable')} · ${e(t?eventDate(t):'')}</p><p>${e(t?.status||'unknown')}${winner?' · Source-reported winner: '+e(winner.player.full_name):''}</p><div class="hero-ctas">${t?a('/tournament/'+t.slug,'Explore the tournament','button button-gold'):''}${a('/pbecast','Open PBEcast archive','button button-glass')}</div></div><div class="hero-caption"><span>SELECTED HISTORY · LIVE SCORING UNAVAILABLE</span><span>EDITORIAL PHOTOGRAPH · CC0</span></div></section>`;
  return hero+source(g)+`<div class="page-body data-body">`+section('The current coverage.',`<div class="data-grid">${unavailable('Current PGA TOUR schedule','PGA TOUR is the primary men’s experience. A current schedule and scoring source is not connected.')}${unavailable('Current LPGA schedule','LPGA shares the same directories and history experience. Current events and scoring are unavailable.')}${unavailable('Live leaderboards','No live state is inferred from historical winners or dates.')}</div>`,'TODAY IN GOLF')+section('The champions in the record.',results(g.results.slice(0,8)),'MAJOR RESULTS / CAPTURED HISTORY')+section('Men’s and women’s majors.',events(g.tournaments.slice(0,8))+a('/tournaments','All captured tournaments'),'CHAMPIONSHIP DIRECTORY')+section('Explore the golfers.',players(g.players.slice(0,6))+a('/players','Player directory'),'PLAYERS / SOURCED IDENTITIES')+section('Championship venues.',courses(g.courses)+a('/courses','Course directory'),'COURSES')+intelligence()+section('The newsroom is in shadow review.',`<p>Frozen evidence packets are held for validation. No automated stories are published.</p>${a('/news','Visit the newsroom')}`,'LATEST NEWS')+`<section class="all-access-ribbon"><div><h2>One membership. All Access.</h2><p>Golf belongs to the existing PropBetEdge network membership.</p></div>${a('/all-access','Membership details','button button-light')}</section></div>`;
 }
 if(path==='/tournaments')return title('PGA TOUR + LPGA MAJOR CONTEXT','The championship record.','Selected major editions, venues and source-reported winners. This is an incomplete archive.')+source(g)+`<div class="page-body data-body">${filters()}${events(g.tournaments)}</div>`;
 if(path==='/players')return title('PLAYERS / SOURCED IDENTITIES','Beyond the leaderboard.','Distinct source identities with a day-precision birth date and golf classification. Unsupported statistics remain unavailable.')+source(g)+`<div class="page-body data-body">${players(g.players)}</div>`;
 if(path==='/courses')return title('COURSES / CHAMPIONSHIP VENUES','The ground beneath the game.','Real course identities connected to captured major editions. Tournament routing and hole specifications remain unavailable.')+source(g)+`<div class="page-body data-body">${courses(g.courses)}</div>`;
 if(detail){const {entity:r,kind}=detail;const history=g.results.filter(x=>kind==='player'?x.player?.id===r.id:kind==='course'?x.tournament?.course?.id===r.id:x.edition_id===r.id);const ts=g.tournaments.filter(t=>kind==='course'?t.course?.id===r.id:history.some(h=>h.edition_id===t.id));
  return title(kind.toUpperCase()+' / SOURCED RECORD',r.full_name||r.name,kind==='tournament'?division(r)+' · '+eventDate(r):kind==='player'?'Country: '+(r.country_name||r.nationality_code||'unavailable')+' · Born: '+(r.birth_date||'unavailable'):[r.locality,r.country_code].filter(Boolean).join(' · '))+source(g)+`<div class="page-body data-body">`+section(kind==='tournament'?'Tournament context':'Observed championship history',`${kind==='tournament'?`<p>Status: ${e(r.status)} · Winner-only metadata coverage</p><p>Venue: ${r.course?a('/course/'+r.course.slug,r.course.name):'Unavailable'}</p>${a('/pbecast?tournament='+r.slug,'Open this edition in PBEcast')}`:''}${results(history)}<p>These records describe the captured sample. They are not career totals, current form or a complete leaderboard.</p>`)+(kind!=='tournament'?section('Connected editions',events(ts)):'')+section(kind==='course'?'Course DNA / descriptive coverage':'Performance coverage',`<div class="data-grid">${kind==='course'?unavailable('Layout and specifications','The venue is sourced. Par, yardage, holes, routing and layout dates are unavailable.'):unavailable('Round scores and scorecards')}${unavailable(kind==='tournament'?'Field, tee times and cut':'Comparable statistical profile')}${unavailable(kind==='tournament'?'Purse and defending champion':'Scoring and course-fit signals')}</div>`)+proof(r)+intelligence()+'</div>';
 }
 if(path==='/pbecast'){
  const t=g.tournaments.find(x=>x.slug===selected)||g.tournaments[0],rs=g.results.filter(r=>r.edition_id===t?.id);
  return title('PBECAST / OBSERVED ARCHIVE','The tournament, in context.','Archive mode. No live action, shot path, active hole or scorecard is inferred.')+source(g)+`<div class="page-body data-body"><label class="cast-selector">Captured edition <select data-cast-select>${g.tournaments.map(x=>`<option value="${e(x.slug)}" ${x.id===t?.id?'selected':''}>${e(x.name)}</option>`).join('')}</select></label><div class="data-cast"><section class="data-card"><span class="micro-label">${e(t?division(t):'TOURNAMENT')}</span><h2>${e(t?.name)}</h2><p>${e(t?eventDate(t):'')}</p><p>${e(t?.status)} · sourced metadata</p>${t?a('/tournament/'+t.slug,'Tournament page'):''}${results(rs)}</section><aside class="data-card"><span class="micro-label">VENUE / COURSE CONTEXT</span><h2>${e(t?.course?.name||'Venue unavailable')}</h2>${t?.course?a('/course/'+t.course.slug,'Course history'):''}${unavailable('Active hole and scorecard')}${unavailable('Live pulse','Winner assertions are historical records, not observed live event progression.')}</aside></div>${section('Captured edition history',events(g.tournaments))}</div>`;
 }
 if(path.startsWith('/majors/')){const key=path.split('/')[2],terms={masters:'Masters','us-womens-open':'Women’s Open',chevron:'Chevron','womens-pga':'Women’s PGA',evian:'Evian','the-open':'Open Championship'};const term=terms[key],ts=term?g.tournaments.filter(t=>t.championship?.replace(/'/g,'’').includes(term)):[];if(ts.length)return title('MAJORS / SELECTED HISTORY',ts[0].championship,'Source-reported editions and champions. Complete championship history is unavailable.')+source(g)+`<div class="page-body data-body">${events(ts)}${results(g.results.filter(r=>ts.some(t=>t.id===r.edition_id)))}</div>`;}
 return null;
}
