import { routes, majors, modules, routeFor, ALL_ACCESS_URL } from './catalog.js';
export const escapeHtml = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link = (path,label,cls='')=>`<a class="${cls}" href="${path}">${label}<span aria-hidden="true">↗</span></a>`;
const empty = (title,detail='Verified source coverage is being established. Scores and statistics will appear when approved data is available.')=>`<section class="empty-state"><span class="pin-mark" aria-hidden="true">⚑</span><div><h2>${title}</h2><p>${detail}</p></div></section>`;
const kicker = text=>`<p class="eyebrow">${text}</p>`;
const sections = ()=>`<section class="editorial-grid" aria-label="Explore golf intelligence">${modules.slice(0,3).map((m,i)=>`<a href="/intelligence" class="editorial-card"><span class="chapter">0${i+1} / ALL ACCESS</span><h3>${m[0]}</h3><p>${m[1]}</p><span class="text-link">Explore the intelligence <span aria-hidden="true">↗</span></span></a>`).join('')}</section>`;
function home(){return `<section class="hero"><div class="hero-visual"><picture><source type="image/avif" srcset="/media/golf-sunrise-640.avif 640w, /media/golf-sunrise-1280.avif 1280w, /media/golf-sunrise-1920.avif 1920w" sizes="100vw"><img src="/media/golf-sunrise-1280.webp" srcset="/media/golf-sunrise-640.webp 640w, /media/golf-sunrise-1280.webp 1280w, /media/golf-sunrise-1920.webp 1920w" sizes="100vw" width="1920" height="960" alt="Real golf-course panorama at sunrise, with mist above a lake" fetchpriority="high"></picture></div><div class="hero-copy">${kicker('PROPBETEDGE / GOLF INTELLIGENCE')}<h1>A deeper view<br> of the game<span class="gold">.</span></h1><p class="hero-deck">From the first tee to the final round.<br>Players, courses and championships. Connected.</p><div class="hero-actions">${link('/pbecast','Explore PBEcast','button gold-button')}${link('/live','Live leaderboard','button outline-button')}</div></div><div class="hero-bottom"><div><span class="micro">THE GLOBAL GAME</span><p>PGA TOUR <span> / </span> LPGA <span> / </span> The majors</p></div><span class="status"><i></i> Live data not connected</span></div></section>
<section class="section live-strip"><div>${kicker('TOURNAMENT WATCH')}<h2>The round starts with context.</h2></div><div class="watch-empty"><span class="micro">LIVE NOW</span><p>No verified live feed is connected.</p>${link('/tournaments','Tournament intelligence','text-link')}</div></section>
<section class="section"><div class="section-heading"><div>${kicker('THE INTELLIGENCE LAYER')}<h2>Know the player.<br>Understand the course.</h2></div><p class="section-intro">A richer perspective on professional golf.<br>Built for the questions a leaderboard cannot answer.</p></div>${sections()}</section>
<section class="championship-band"><div>${kicker('MAJOR CHAMPIONSHIPS')}<h2>The stages.<br>The stakes.<br>The history.</h2><p>Men’s and women’s championship golf,<br>given the perspective it deserves.</p>${link('/majors','Explore the majors','button outline-button')}</div><div class="major-columns"><div><span class="micro">MEN’S MAJORS</span>${majors.filter(m=>m[1]==='Men').map(m=>link('/majors/'+m[2],m[0],'major-link')).join('')}</div><div><span class="micro">WOMEN’S MAJORS</span>${majors.filter(m=>m[1]==='Women').map(m=>link('/majors/'+m[2],m[0],'major-link')).join('')}</div></div></section>
<section class="section lower-grid"><div>${kicker('WORLD RANKINGS')}<h2>Every move has a history.</h2><p>Ranking snapshots will connect the current picture to the career behind it.</p>${link('/rankings','Rankings','text-link')}</div><div>${kicker('FROM THE NEWSROOM')}<h2>Evidence before headlines.</h2><p>No articles published yet. Reporting begins when verified golf data supports a meaningful story.</p>${link('/news','Visit the newsroom','text-link')}</div></section>
<section class="membership-banner"><div>${kicker('PROPBETEDGE ALL ACCESS')}<h2>Your membership.<br>A wider view of golf.</h2><p>Golf Intelligence is included with the network’s All Access / Pro Club membership.</p></div>${link('/all-access','Discover All Access','button gold-button')}</section>`;}
function page(route){
 const head=`<section class="page-heading">${kicker('GOLF INTELLIGENCE / '+escapeHtml(route.label).toUpperCase())}<h1>${escapeHtml(route.title)}</h1><p>${escapeHtml(route.description)}</p></section>`;
 let body='';
 if(route.path==='/majors') body=`<div class="major-directory">${['Men','Women'].map(g=>`<section><h2>${g==='Men'?'Men’s':'Women’s'} major championships</h2>${majors.filter(m=>m[1]===g).map(m=>`<a href="/majors/${m[2]}" class="directory-row"><h3>${m[0]}</h3><span>History awaiting verified data ↗</span></a>`).join('')}</section>`).join('')}</div>`;
 else if(route.path==='/all-access') body=`<section class="access-layout"><div>${kicker('ONE NETWORK MEMBERSHIP')}<h2>All of golf.<br>All of PropBetEdge.</h2><p>Player DNA, Course DNA, Course Fit, advanced PBEcast and historical intelligence belong to the existing All Access membership.</p><p class="coverage-note">Premium golf modules are not available yet. Membership verification will connect through the PropBetEdge network.</p>${link(ALL_ACCESS_URL,'Visit PropBetEdge All Access','button pine-button')}</div><aside class="access-list"><h3>Built into your membership</h3>${['Player intelligence','Course intelligence','Championship history','Advanced tournament context','Every current and future PBE Pro sport'].map(x=>`<p><span aria-hidden="true">✓</span> ${x}</p>`).join('')}<p class="micro">NO GOLF-ONLY SUBSCRIPTION</p></aside></section>`;
 else if(route.path==='/intelligence') body=`<p class="coverage-note">Included with All Access. These modules are in development; no analytical values are available yet.</p><div class="intelligence-grid">${modules.map(m=>`<section class="intelligence-card">${kicker('ALL ACCESS / IN DEVELOPMENT')}<h2>${m[0]}</h2><p>${m[2]}</p><span class="micro">AWAITING VERIFIED DATA</span></section>`).join('')}</div>`;
 else if(route.path==='/pbecast') body=`<div class="cast-layout"><section class="cast-stage">${kicker('ACTIVE HOLE')}<h2>A clearer view of the round.</h2><div class="contour-field" aria-hidden="true"><span>⚑</span></div><p>No active hole or shot events are available.</p><p class="micro">SHOT SEQUENCES REQUIRE OBSERVED SOURCE EVENTS</p></section><aside class="cast-rail"><h2>Tournament pulse</h2><p>Leader changes, scoring runs and movement will appear from verified events.</p><div class="rail-divider"></div><h3>Player live card</h3><p>Choose a verified tournament and player when coverage is available.</p>${link('/all-access','Advanced view · All Access','text-link')}</aside></div>`;
 else { const filters=['/today','/live','/tournaments'].includes(route.path) ? `<div class="filter-row" role="group" aria-label="Tour coverage">${['All tours','PGA TOUR','LPGA','Global'].map((t,i)=>`<button type="button" class="filter-button ${i===0?'selected':''}" aria-pressed="${i===0}" data-tour="${t}">${t}</button>`).join('')}</div><p class="filter-description" role="status">Showing all tour coverage.</p>`:'';
 body=filters+empty(route.empty || 'Verified data is unavailable.')+(route.notFound?link('/','Return home','button pine-button'):`<div class="coverage-panel"><h3>Coverage with a clear basis</h3><p>Historical and live coverage may differ by tour, tournament and season. Unavailable information stays unavailable.</p><span class="micro">SOURCE • EFFECTIVE DATE • SAMPLE • PROVENANCE</span></div>`);}
 return head+`<div class="page-body">${body}</div>`;
}
export function render(path='/'){
 const route=routeFor(path);
 return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="masthead"><a class="brand" href="/" aria-label="PropBetEdge Golf home"><span class="brand-name">PROP<span>BET</span>EDGE<span class="brand-tick">↗</span></span><span class="brand-sub">GOLF INTELLIGENCE</span></a><div class="masthead-right"><span class="edition">THE GLOBAL GOLF PERSPECTIVE</span><a class="access-link" href="/all-access">All Access <span aria-hidden="true">↗</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="primary-navigation">Menu <span aria-hidden="true">☰</span></button></div></div><nav id="primary-navigation" class="primary-nav" aria-label="Primary">${routes.filter(r=>r.path!=='/'&&r.path!=='/all-access').map(r=>`<a href="${r.path}" ${path===r.path?'aria-current="page"':''}>${r.label}</a>`).join('')}</nav></header><main id="main">${path==='/'?home():page(route)}</main><footer class="site-footer"><a class="footer-brand" href="/">PROPBETEDGE <span>GOLF INTELLIGENCE</span></a><p>Independent golf intelligence. No affiliation with any tour or championship.</p><p class="photo-credit">Editorial photograph: Golf Course Sunrise · Dimitrios Savva / Jarod Guest / <a href="https://polyhaven.com/a/golf_course_sunrise">Poly Haven</a> · <a href="https://creativecommons.org/publicdomain/zero/1.0/">CC0</a>. No tournament venue association.</p><div><a href="/all-access">All Access</a><a href="/news">Newsroom</a><span>© ${new Date().getUTCFullYear()} PropBetEdge</span></div></footer>`;
}

