// Site shell + router. `data` = {index, players, editions, courses (Maps of public docs), stories}.
import * as P from './pages.js';
import {nextCueHtml} from './pages.js';
import {e,go,kicker} from './ui.js';
import * as A from './article.js';
import {SITE,fullTitle,ogImage,photoNode,personNode,courseNode,eventNode} from './seo.js';
import {videoNode} from './video.js';
import {familyFooterHtml} from './network.js';
import {allAccessPage} from './all-access-page.js';
import {picksPage} from './picks-ui.js';
export const escapeHtml=e;
export const ALL_ACCESS_URL='https://propbetedge.ai/pro';
export const NAV=[['/today','Today'],['/live','Live'],['/tournaments','Tournaments'],['/players','Players'],['/matchups','Matchups'],['/courses','Courses'],['/majors','Majors'],['/pbecast','PBEcast'],['/picks','Picks & Record'],['/news','News'],['/intelligence','Intelligence'],['/search','Search']];
const notFound=()=>`<section class="page-heading data-heading"><div>${kicker('404')}<h1>This page is out of bounds.</h1><p>The page or record you asked for is not in coverage.</p>${go('/','Return home','button button-gold')}</div></section>`;
// Index only pages that pass a quality floor; thin entities stay noindex. Every route carries its own
// title, description, canonical, social image and connected JSON-LD graph (see seo.js).
export function route(path,data){
 const ix=data?.index,clean=path==='/'?'/':path.replace(/\/$/,'');const [,kind,id]=clean.split('/');
 const page=(main,title,description,indexable=true,seo={})=>({main,title,description,indexable,fullTitle:fullTitle(clean,title),...seo});
 if(!ix)return page(notFound(),'Not found','Golf intelligence',false);
 if(clean==='/')return page(P.home(ix),'Golf Intelligence','Golf leaderboards, round scores, Player DNA, Course DNA and championship history across the PGA TOUR, LPGA and every major.',true,{feed:true});
 if(clean==='/today')return page(P.today(ix),'Today in Golf','PGA TOUR and LPGA schedules, this week’s tournaments and the latest results.',true,{crumbs:[['Today','/today']]});
 if(clean==='/live')return page(P.live(ix),'Live Golf','Live scoring status and the latest final leaderboard.',false);
 if(clean==='/tournaments')return page(P.tournaments(ix),'Golf Tournaments','Every tournament edition in coverage with champions and leaderboards.',true,{crumbs:[['Tournaments','/tournaments']],pageType:'CollectionPage'});
 if(clean==='/players')return page(P.players(ix),'Golf Players','Player directory with results, majors and Player DNA.',true,{crumbs:[['Players','/players']],pageType:'CollectionPage'});
 if(clean==='/courses')return page(P.courses(ix),'Golf Courses','Championship courses with history, setups and Course DNA.',true,{crumbs:[['Courses','/courses']],pageType:'CollectionPage'});
 if(clean==='/majors')return page(P.majorsIndex(ix),'Major Championships','Every edition of the men’s and women’s majors.',true,{crumbs:[['Majors','/majors']],pageType:'CollectionPage'});
 if(clean==='/matchups')return page(P.matchupsIndex(ix),'Golf Matchups','Compare any two golfers side by side.',true,{crumbs:[['Matchups','/matchups']]});
 if(clean==='/pbecast')return page(P.pbecast(ix,data.editions?.get(ix.recent.find(x=>x.coverage==='full_field')?.slug)||null),'PBEcast','Tournament replays from published results.',false);
 if(clean==='/news'){const n=data.news?.index||[];return page(A.newsIndex(n,{legacy:data.stories||[]}),'Golf News','Golf news from the PropBetEdge Golf Desk: previews, round recaps, finals and data stories where every number traces to a frozen fact.',Boolean(n.length),{crumbs:[['News','/news']],pageType:'CollectionPage',feed:true});}
 if(kind==='news'&&id&&data.article?.slug===id){const art=data.article,url=SITE+'/news/'+art.slug;
  const analysis=['course_intelligence','player_form','major_history'].includes(art.type);
  const ids=art.entities.map(x=>x.type==='player'?SITE+x.href+'#person':x.type==='course'?SITE+x.href+'#course':x.type==='tournament'?SITE+x.href+'#event':null).filter(Boolean);
  const heroId=url+'#hero',hero=art.hero?.photo?photoNode(heroId,art.hero.photo,art.hero.name):null;
  const words=art.sections.flatMap(s=>s.paragraphs).map(p=>p.map(x=>x.v).join('')).join(' ').split(/\s+/).length;
  const node={'@type':analysis?'AnalysisNewsArticle':'NewsArticle','@id':url+'#article',headline:art.headline_text.slice(0,110),description:art.dek_text,datePublished:art.published_at,dateModified:art.updated_at,author:{'@id':SITE+'/#desk'},publisher:{'@id':SITE+'/#desk'},mainEntityOfPage:{'@id':url+'#webpage'},isPartOf:{'@id':SITE+'/#website'},image:[{'@id':url+'#primaryimage'},...(hero?[{'@id':heroId}]:[])],articleSection:art.category,inLanguage:'en-US',isAccessibleForFree:true,wordCount:words,about:ids.slice(0,3).map(x=>({'@id':x})),mentions:ids.slice(3).map(x=>({'@id':x})),...(art.video?{video:{'@id':url+'#video'}}:{}),...(art.corrections?.length?{correction:art.corrections.map(c=>({'@type':'CorrectionComment',datePublished:c.at,text:c.facts.map(f=>`${f.label} changed from ${f.was} to ${f.now??'removed'}`).join('; ')}))}:{})};
  const refNodes=art.entities.filter(x=>['player','course','tournament'].includes(x.type)).map(x=>x.type==='player'?{'@type':'Person','@id':SITE+x.href+'#person',name:x.name,url:SITE+x.href}:x.type==='course'?{'@type':'GolfCourse','@id':SITE+x.href+'#course',name:x.name,url:SITE+x.href}:{'@type':'SportsEvent','@id':SITE+x.href+'#event',name:x.name,url:SITE+x.href,sport:'Golf'});
  return page(A.articlePage(art,{related:data.related||[],market:data.market||null}),art.seo?.title||art.headline_text,art.seo?.description||art.dek_text,art.status==='published',{crumbs:[['News','/news'],[art.headline_text,'/news/'+art.slug]],mainEntity:url+'#article',nodes:[node,hero,...refNodes,...(art.video?[videoNode(art.video,url+'#video')]:[])],og:{url:ogImage('news',art.slug),width:1200,height:630,alt:art.headline_text,year:art.published_at,photos:art.hero?.photo?[{...art.hero.photo,derivatives:true}]:[]},socialTitle:art.seo?.social||art.headline_text,article:{published:art.published_at,modified:art.updated_at,section:art.category,tags:art.entities.filter(x=>x.type!=='matchup').map(x=>x.name)},feed:true});}
 if(clean==='/intelligence')return page(P.intelligence(ix),'Golf Intelligence Methodology','How Player DNA, Course DNA, Bag DNA and Course Fit are calculated, with sources and sample rules.',true,{crumbs:[['Methodology','/intelligence']]});
 if(clean==='/rankings')return page(P.rankings(ix),'Golf Rankings','Ranking source status.',false);
 if(clean==='/search')return page(P.search(),'Search','Search golfers, tournaments and courses.',false);
 if(clean==='/picks')return page(picksPage(),'Golf Picks','Golf Picks and Track Record: full-field finish probabilities locked before the first tee and graded after the official result. All Access.',false,{crumbs:[['Picks','/picks']]});
 if(clean==='/all-access')return page(allAccessPage(),'PropBetEdge All Access on Golf','Golf intelligence is one desk in the PropBetEdge network. All Access includes 10 sports plus Command Center, Compare, Markets and Predictions for $29/month.',true,{crumbs:[['All Access','/all-access']]});
 if(kind==='majors'&&id){const html=P.series(id,ix);if(html)return page(html,P.seriesName(id),`${P.seriesName(id)}: every champion, leaderboard and edition in our record.`,true,{crumbs:[['Majors','/majors'],[P.seriesName(id),clean]],pageType:'CollectionPage',og:{url:ogImage('majors',id),width:1200,height:630,alt:P.seriesName(id)}});}
 if(kind==='tournament'){const d=data.editions?.get(id);if(d){const full=d.leaderboard.length>0,w=d.leaderboard.find(r=>r.winner);
  const c=d.course?{...d.course,...(data.courses?.get(d.course.slug)||{})}:null;
  return page(P.edition(d,ix),d.name,`${d.name}${d.course?' at '+d.course.name:''}: ${full?'final leaderboard, round scores and ':''}champion${w?.player?' '+w.player.name:''}.`,full||d.status==='completed',{crumbs:[['Tournaments','/tournaments'],[d.name,clean]],mainEntity:SITE+clean+'#event',nodes:[eventNode(d),c?courseNode(c):null,...(w?.player?[{'@type':'Person','@id':SITE+'/player/'+w.player.slug+'#person',name:w.player.name,url:SITE+'/player/'+w.player.slug}]:[])],og:{url:ogImage('tournament',d.slug),width:1200,height:630,alt:d.name,photos:[c?.photo]}});}}
 if(kind==='player'){const d=data.players?.get(id);if(d){const ok=d.summary.events_observed>=3||d.summary.wins_observed>0;const img=d.photo?.sha256?SITE+clean+'#photo':null;
  return page(P.player(d,ix),d.name,`${d.name}${d.country?' ('+d.country+')':''}: results, majors, course history and Player DNA from ${d.summary.events_observed} observed events.`,ok,{pageType:'ProfilePage',crumbs:[['Players','/players'],[d.name,clean]],mainEntity:SITE+clean+'#person',nodes:[personNode(d,{image:img}),img?photoNode(img,d.photo,d.name):null],og:{url:ogImage('player',d.slug),width:1200,height:630,alt:d.name,photos:[d.photo]}});}}
 if(kind==='course'){const d=data.courses?.get(id);if(d){const img=d.photo?.sha256?SITE+clean+'#photo':null;
  return page(P.course(d,ix),d.name,`${d.name}: ${d.editions.length} championship editions, setups, Course DNA and champions.`,d.editions.length>=2,{crumbs:[['Courses','/courses'],[d.name,clean]],mainEntity:SITE+clean+'#course',nodes:[courseNode(d,{image:img}),img?photoNode(img,d.photo,d.name):null],og:{url:ogImage('course',d.slug),width:1200,height:630,alt:d.name,photos:[d.photo]}});}}
 if(kind==='matchups'&&data.matchup){const m=data.matchup;return page(P.matchup(m),`${m.a.name} vs ${m.b.name}`,`${m.a.name} vs ${m.b.name}: side-by-side Player DNA, records and shared events.`,true,{crumbs:[['Matchups','/matchups'],[`${m.a.name} vs ${m.b.name}`,clean]],about:[SITE+'/player/'+m.a.slug+'#person',SITE+'/player/'+m.b.slug+'#person'],nodes:[{'@type':'Person','@id':SITE+'/player/'+m.a.slug+'#person',name:m.a.name,url:SITE+'/player/'+m.a.slug},{'@type':'Person','@id':SITE+'/player/'+m.b.slug+'#person',name:m.b.name,url:SITE+'/player/'+m.b.slug}],og:{url:ogImage('matchup',m.a.slug+'--'+m.b.slug),width:1200,height:630,alt:`${m.a.name} vs ${m.b.name}`,photos:[m.a.photo,m.b.photo]}});}
 return page(notFound(),'Not found','The requested page is not in coverage.',false);
}
export function shell(path,main,ix=null){
 const nav=NAV.map(([href,label])=>`<a href="${href}" ${path===href||path.startsWith(href+'/')?'aria-current="page"':''}>${label}</a>`).join('');
 return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="masthead"><a class="brand" href="/" aria-label="PropBetEdge Golf home"><span class="brand-name">PROP<span>BET</span>EDGE<span class="brand-tick">/</span></span><span class="brand-sub">GOLF INTELLIGENCE</span></a><div class="masthead-right"><span class="edition">PGA TOUR · LPGA · MAJORS</span><a class="access-link account-status" href="/all-access" data-account-status data-account-view="checking" aria-label="PropBetEdge account and All Access status"><i class="account-status-dot" aria-hidden="true"></i><span class="account-status-copy"><b data-account-label>ACCOUNT</b><small data-account-detail>CHECKING ACCESS</small></span><span class="account-status-arrow" aria-hidden="true">↗</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="primary-navigation">Menu <span aria-hidden="true">☰</span></button></div></div><nav id="primary-navigation" class="primary-nav" aria-label="Primary">${nav}</nav>${ix?nextCueHtml(ix):''}</header><main id="main" class="${path==='/'?'main-home':''}">${main}</main><footer class="site-footer"><div class="footer-main"><a class="footer-brand" href="/">PROPBETEDGE <span>GOLF INTELLIGENCE</span></a><p>Independent golf intelligence. No affiliation with any tour or championship.</p><div class="footer-links"><a href="https://x.com/PROPBETEDGE">@PROPBETEDGE</a><a href="/majors">Majors</a><a href="/news">Newsroom</a><a href="/intelligence">Methodology</a><a href="https://propbetedge.ai/about">About PropBetEdge</a><a href="https://propbetedge.ai/terms">Terms</a><a href="https://propbetedge.ai/legal">Legal</a><a href="https://propbetedge.ai/support">Support</a></div></div>${familyFooterHtml()}<div class="footer-bottom"><p class="photo-credit">DATA · <a href="https://propsports.proptechusa.ai">PropSports</a>. Results adapted in part from Wikipedia contributors (CC BY-SA 4.0). Forecasts: NOAA National Weather Service. Player and course photographs credited individually (Wikimedia Commons). Home background: Golf Course Sunrise · Dimitrios Savva / Jarod Guest / <a href="https://polyhaven.com/a/golf_course_sunrise">Poly Haven</a> · <a href="https://creativecommons.org/publicdomain/zero/1.0/">CC0</a>, not a tournament venue.</p><span>© ${new Date().getFullYear()} PROPBETEDGE</span></div></footer>`;
}
export function render(path='/',data=null){return shell(path,route(path,data).main,data?.index);}
