import {test,expect} from '@playwright/test';import AxeBuilder from '@axe-core/playwright';import {routes,majors,routeFor} from '../../src/lib/catalog.js';
const paths=[...routes.map(r=>r.path),...majors.map(m=>'/majors/'+m[2])];
for(const width of [320,360,390,430,768,1024,1440]){
 for(const path of paths)test(width+' '+path+' layout/accessibility/console',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
  await page.setViewportSize({width,height:900});await page.goto(path);await expect(page.locator('h1')).toHaveCount(1); await expect(page.getByRole('heading',{level:1})).not.toHaveAccessibleName(''); const route=routeFor(path); await expect(page).toHaveTitle(path==='/'?'Golf Intelligence | PropBetEdge':route.label+' | PropBetEdge Golf');
  const overflow=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,offenders:[...document.querySelectorAll('body *')].map(el=>({tag:el.tagName,cls:String(el.className||''),left:Math.round(el.getBoundingClientRect().left),right:Math.round(el.getBoundingClientRect().right),width:Math.round(el.getBoundingClientRect().width),parent:el.parentElement?.className,parentLeft:Math.round(el.parentElement?.getBoundingClientRect().left||0),parentRight:Math.round(el.parentElement?.getBoundingClientRect().right||0),display:getComputedStyle(el.parentElement).display})).filter(el=>el.right>innerWidth+1||el.left< -1).slice(0,8)}));expect(overflow.scroll<=overflow.width,JSON.stringify(overflow)).toBe(true);
  expect(errors).toEqual([]);
  const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(results.violations).toEqual([]);
  if(path==='/'&&[390,1440].includes(width)){await expect(page.locator('.home-hero-image img')).toHaveJSProperty('complete',true);expect(await page.locator('.home-hero-image img').evaluate(image=>image.naturalWidth)).toBeGreaterThan(0);await page.screenshot({path:'docs/evidence/screenshots/home-'+width+'.png',fullPage:true});}
  if(path==='/pbecast'&&width===1440)await page.screenshot({path:'docs/evidence/screenshots/pbecast-1440.png',fullPage:true});
 });
}
test('mobile menu navigates and Escape restores focus',async({page})=>{await page.setViewportSize({width:390,height:850});await page.goto('/');const menu=page.getByRole('button',{name:'Menu'});await menu.click();await expect(menu).toHaveAttribute('aria-expanded','true');await page.keyboard.press('Escape');await expect(menu).toBeFocused();await expect(menu).toHaveAttribute('aria-expanded','false');await menu.click();await page.getByRole('navigation',{name:'Primary'}).getByRole('link',{name:'Live',exact:true}).click();await expect(page).toHaveURL(/\/live$/);});
test('today page distinguishes primary and first-class tour coverage without inventing schedule data',async({page})=>{await page.goto('/today');await expect(page.locator('.tour-pills')).toContainText('PGA TOUR');await expect(page.locator('.tour-pills')).toContainText('LPGA');await expect(page.getByText('No verified tournament schedule is available yet.')).toBeVisible();});
test('All Access communicates network entitlement without golf checkout',async({page})=>{await page.goto('/all-access');await expect(page.getByRole('link',{name:'Manage All Access membership'})).toHaveAttribute('href','https://propbetedge.ai/pro');await expect(page.getByText('NO GOLF PRO CHECKOUT')).toBeVisible();expect(await page.locator('body').innerText()).not.toMatch(/Golf Pro \$/);});
test('built shell works without JavaScript and first response metadata',async({browser})=>{const context=await browser.newContext({javaScriptEnabled:false});const page=await context.newPage();const response=await page.goto('http://127.0.0.1:5175/majors');expect(response.status()).toBe(200);await expect(page.getByRole('heading',{level:1})).toHaveAccessibleName(/History’s greatest stages/);await expect(page).toHaveTitle('Majors | PropBetEdge Golf');await expect(page.locator('meta[name=robots]')).toHaveAttribute('content','noindex,follow');await context.close();});
test('major detail pages expose canonical editions and winner-only coverage',async({page})=>{await page.goto('/majors/masters');await expect(page.getByRole('heading',{level:1})).toHaveAccessibleName('Masters Tournament');await expect(page.getByRole('link',{name:'2026 Masters Tournament'}).first()).toBeVisible();await expect(page.getByText('Source-reported winners · selected editions only')).toBeVisible();});
