import {test,expect} from '@playwright/test';import AxeBuilder from '@axe-core/playwright';import fs from 'node:fs';
// Pages are chosen from the exported projection so QA always exercises real, populated entities.
const b=JSON.parse(fs.readFileSync('data/public/bundle.json','utf8'));const ix=b.index;
const full=div=>ix.editions.find(e=>e.coverage==='full_field'&&e.division===div);
const topPlayer=div=>ix.players.filter(p=>p.division===div).sort((a,c)=>(c.photo?.derivatives?1:0)-(a.photo?.derivatives?1:0)||c.events_observed-a.events_observed)[0];
const fm=ix.featured_matchups?.[0];
const PAGES=['/','/today','/live','/tournaments','/players','/courses','/majors','/matchups','/pbecast','/news','/intelligence','/search','/all-access','/majors/masters','/majors/evian',
 full('men')&&'/tournament/'+full('men').slug,full('women')&&'/tournament/'+full('women').slug,'/player/'+topPlayer('men').slug,'/player/'+topPlayer('women').slug,'/course/'+ix.courses[0].slug,fm&&`/matchups/${fm.a.slug}/${fm.b.slug}`].filter(Boolean);
export {PAGES};
const WIDTHS=(process.env.QA_WIDTHS||'320,360,390,430,768,1024,1440').split(',').map(Number);
for(const width of WIDTHS)for(const path of PAGES)test(`${width} ${path}`,async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!/status of 403/.test(m.text()))errors.push(m.text());});
 await page.setViewportSize({width,height:900});const res=await page.goto(path,{waitUntil:'networkidle'});expect(res.status()).toBe(200);
 await expect(page.locator('h1')).toHaveCount(1);await expect(page.getByRole('heading',{level:1})).not.toHaveAccessibleName('');
 const ov=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth,off:[...document.querySelectorAll('body *')].filter(el=>{const r=el.getBoundingClientRect();return r.width&&(r.right>innerWidth+1||r.left<-1)&&!el.closest('.table-wrap,.hole-strip')}).slice(0,5).map(el=>el.tagName+'.'+el.className)}));
 expect(ov.scroll<=ov.width,JSON.stringify(ov)).toBe(true);
 const inlineStyles=await page.locator('[style]').count();expect(inlineStyles).toBe(0);const broken=await page.evaluate(async()=>{const imgs=[...document.images];for(const i of imgs){i.loading='eager';}await Promise.all(imgs.map(i=>i.complete?null:new Promise(r=>{i.onload=i.onerror=r;setTimeout(r,8000);})));return imgs.filter(i=>!i.naturalWidth).map(i=>i.currentSrc||i.src);});
 expect(broken).toEqual([]);expect(errors).toEqual([]);
 expect(await page.locator('body').innerText()).not.toMatch(/\bwill appear\b|\bwhen connected\b|coming soon|lorem ipsum/i);
 const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(axe.violations.map(v=>v.id+': '+v.nodes.slice(0,2).map(n=>n.target).join(' | '))).toEqual([]);
 if([390,1440].includes(width)&&process.env.QA_SHOTS)await page.screenshot({path:`docs/evidence/screenshots/${(path.replace(/[^a-z0-9]+/gi,'-')||'home').slice(0,60)}-${width}.png`,fullPage:false});
});
test('mobile menu opens, closes with Escape and restores focus',async({page})=>{await page.setViewportSize({width:390,height:850});await page.goto('/');const menu=page.getByRole('button',{name:'Menu'});await menu.click();await expect(menu).toHaveAttribute('aria-expanded','true');await expect(page.locator('#primary-navigation')).toBeVisible();await page.keyboard.press('Escape');await expect(menu).toHaveAttribute('aria-expanded','false');await expect(menu).toBeFocused();});
test('tournament filters change visible rows',async({page})=>{await page.goto('/tournaments');await page.locator('[data-filter="division"]').selectOption('women');await page.locator('[data-filter="major"]').selectOption('true');expect(await page.locator('tbody tr[data-division="men"]:visible').count()).toBe(0);expect(await page.locator('tbody tr[data-division="women"]:visible').count()).toBeGreaterThan(20);});
test('player directory search and DNA sort use real data',async({page})=>{await page.goto('/players');const name=topPlayer('women').name;await page.locator('[data-player-search]').fill(name.split(' ')[0]);await expect(page.locator('[data-player-grid]')).toContainText(name);await page.locator('[data-player-search]').fill('');await page.locator('select[name="sort"]').selectOption('scoring');await expect(page.locator('[data-filter-count]')).toContainText('Showing');});
test('matchup finder canonicalizes A vs B and B vs A to one URL',async({page})=>{test.skip(!fm,'no featured matchup');await page.goto('/matchups');await page.locator('input[name="a"]').fill(fm.b.name);await page.locator('input[name="b"]').fill(fm.a.name);await page.getByRole('button',{name:'Compare'}).click();await expect(page).toHaveURL(new RegExp(`/matchups/${fm.a.slug}/${fm.b.slug}$`));await expect(page.locator('.vs-hero')).toContainText(fm.a.name);});
test('reversed matchup URL redirects to canonical order',async({page})=>{test.skip(!process.env.QA_BASE,'needs the Vercel rewrite (production run)');const ps=ix.players.slice(5,7).map(p=>p.slug).sort();await page.goto(`/matchups/${ps[1]}/${ps[0]}`);await expect(page).toHaveURL(new RegExp(`/matchups/${ps[0]}/${ps[1]}$`));await expect(page.locator('main')).toContainText(/shared events/i,{timeout:10000});});
test('PBEcast switches to a women’s edition in archive mode without fake shots',async({page})=>{const ed=full('women');await page.goto('/pbecast');await page.locator('[data-cast-select]').selectOption(ed.slug);await expect(page).toHaveURL(new RegExp('tournament='+ed.slug));await expect(page.locator('.cast-head h1')).toHaveText(ed.name);expect(await page.locator('main').innerText()).not.toMatch(/shot trajectory|LIVE NOW/i);});
test('static entity content works without JavaScript',async({browser})=>{const c=await browser.newContext({javaScriptEnabled:false});const p=await c.newPage();const ed=full('men');await p.goto('/tournament/'+ed.slug);await expect(p.locator('table.board')).toBeVisible();expect(await p.locator('table.board tbody tr').count()).toBeGreaterThan(40);await c.close();});
test('premium modules stay locked for a signed-out reader and API denies',async({page,request})=>{await page.goto('/player/'+topPlayer('men').slug);await expect(page.locator('[data-premium="player-dna"] .premium-status')).toContainText(/Free reader|verification unavailable/i,{timeout:10000});const r=await request.get('/api/v1/intelligence/player-dna/'+topPlayer('men').slug);expect(r.status()).toBe(403);const body=await r.json();expect(body.data).toBeUndefined();});
test('static HTML carries no premium DNA values',async({request})=>{const html=await (await request.get('/player/'+topPlayer('men').slug)).text();expect(html).not.toMatch(/"cohort_size"|premium-json/);});
test('internal links on hub pages resolve',async({page,request})=>{const seen=new Set();for(const hub of ['/','/majors','/courses']){await page.goto(hub);for(const href of await page.locator('main a[href^="/"]').evaluateAll(as=>as.map(a=>a.getAttribute('href'))))seen.add(href.split('?')[0]);}const sample=[...seen].slice(0,60);for(const h of sample){const r=await request.get(h);expect(r.status(),h).toBe(200);}});
test('SEO: canonical, robots, sitemap and JSON-LD on qualified pages',async({request})=>{const ed=full('men');const html=await (await request.get('/tournament/'+ed.slug)).text();expect(html).toContain(`<link rel="canonical" href="https://golf.propbetedge.ai/tournament/${ed.slug}">`);expect(html).toContain('index,follow');expect(html).toContain('"@type":"SportsEvent"');const sm=await (await request.get('/sitemap.xml')).text();expect(sm).toContain('/tournament/'+ed.slug);const live=await (await request.get('/live')).text();expect(live).toContain('noindex');});
