import {test,expect} from '@playwright/test';import AxeBuilder from '@axe-core/playwright';import fs from 'node:fs';
const g=JSON.parse(fs.readFileSync('data/public/graph.json','utf8'));
const entities=[...g.players.map(x=>({path:'/player/'+x.slug,name:x.full_name})),...g.courses.map(x=>({path:'/course/'+x.slug,name:x.name})),...g.tournaments.map(x=>({path:'/tournament/'+x.slug,name:x.name}))];
for(const width of [320,360,390,430,768,1024,1440])for(const entity of entities)test(`${width} canonical ${entity.path}`,async({page})=>{
 const errors=[];page.on('pageerror',err=>errors.push(err.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.setViewportSize({width,height:900});const response=await page.goto(entity.path);expect(response.status()).toBe(200);await expect(page.getByRole('heading',{level:1})).toHaveAccessibleName(entity.name);await expect(page).toHaveTitle(entity.name+' | PropBetEdge Golf');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.getByText('Wikidata structured data · CC0')).toBeVisible();
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);expect(errors).toEqual([]);
});
test('tour filter changes actual visible canonical editions by keyboard',async({page})=>{await page.goto('/tournaments');const women=page.getByRole('button',{name:'Women’s majors',exact:true});await women.focus();await page.keyboard.press('Enter');await expect(women).toHaveAttribute('aria-pressed','true');expect(await page.locator('[data-event-division="men"]:visible').count()).toBe(0);expect(await page.locator('[data-event-division="women"]:visible').count()).toBeGreaterThan(0);});
test('PBEcast selects a real women’s edition in archive mode',async({page})=>{const event=g.tournaments.find(t=>t.major_division==='women');await page.goto('/pbecast');await page.locator('[data-cast-select]').selectOption(event.slug);await expect(page).toHaveURL(new RegExp('tournament='+event.slug));await expect(page.locator('.data-cast')).toContainText(event.name);await expect(page.getByText('Archive mode.',{exact:false})).toBeVisible();expect(await page.locator('.data-cast').innerText()).not.toMatch(/shot trajectory|LIVE NOW/);});
test('canonical profile has static sourced content without JavaScript',async({browser,baseURL})=>{const c=await browser.newContext({javaScriptEnabled:false});const p=await c.newPage();const player=g.players[0];await p.goto(baseURL+'/player/'+player.slug);await expect(p.getByRole('heading',{level:1})).toHaveAccessibleName(player.full_name);await expect(p.getByRole('table')).toBeVisible();await c.close();});
test('same-origin health and public graph prove SPORTS connectivity',async({request})=>{const response=await request.get('/api/health');expect(response.status()).toBe(200);const health=await response.json();expect(health.graph_connected).toBe(true);expect(health.project).toBe('tkmlnhmylqnttmnsnief');const data=await (await request.get('/api/v1/players')).json();expect(data.data.length).toBeGreaterThan(0);expect(data.data[0].provenance.sha256).toMatch(/^[a-f0-9]{64}$/);});
test('anonymous premium request exposes no values and never permits shared caching',async({request})=>{const r=await request.get('/api/v1/intelligence/player-dna/'+g.players[0].id);expect(r.status()).toBe(403);expect(r.headers()['cache-control']).toBe('no-store');expect(await r.json()).not.toHaveProperty('data');});
test('membership UI reflects authorized network verdict and keeps unsupported intelligence unavailable',async({page})=>{await page.route('**/api/v1/membership',r=>r.fulfill({json:{membership:{sport:'golf',state:'all_access',entitled:true,access_source:'all_access'}}}));await page.goto('/all-access');await expect(page.locator('.entitlement-status>.state')).toHaveText('ALL ACCESS VERIFIED');await expect(page.locator('.membership-live')).toContainText('Statistical intelligence is unavailable');});
test('membership UI remains locked if authority cannot be reached',async({page})=>{await page.route('**/api/v1/membership',r=>r.abort());await page.goto('/all-access');await expect(page.locator('.entitlement-status>.state')).toHaveText('VERIFICATION UNAVAILABLE');await expect(page.locator('.membership-live')).toContainText('Premium access remains locked');});
