import test from 'node:test';import assert from 'node:assert/strict';
import {liveState,freshness,publicEvent,orderEvents,leaders,toParNum,FRESH_SECONDS} from '../workers/shared/live.js';
import {normalizeCompetitor} from '../workers/golf-ingest/src/live.js';
const NOW=Date.parse('2026-10-01T22:00:00Z');
const ago=s=>new Date(NOW-s*1000).toISOString();
const st=(name,state,period=1,completed=false)=>({name,state,period,completed,detail:''});
const P=(o={})=>({slug:'a',name:'A',status:'active',position_num:1,position_display:'1',tied:false,total_to_par:-5,today_to_par:-5,today_strokes:31,thru:9,rounds:[{round:1,strokes:31,to_par:-5,complete:false}],...o});
const snap=(event_status,fetched,players=[P()])=>({fetched_at:fetched,event_status,players,edition:{name:'X'}});
test('live: a date window alone is never live',()=>{assert.equal(liveState(null,NOW).state,'unavailable');assert.equal(liveState(snap(st('STATUS_SCHEDULED','pre'),ago(60),[P({thru:null,rounds:[],total_to_par:null})]),NOW).state,'pre');});
test('live: ESPN in-progress + fresh posted scores = LIVE with the round',()=>{const s=liveState(snap(st('STATUS_IN_PROGRESS','in',1),ago(4*60)),NOW);assert.equal(s.state,'live');assert.equal(s.label,'LIVE SCORING · ROUND 1');assert.equal(s.freshness,'fresh');});
test('live: stale snapshot is never labelled live',()=>{const s=liveState(snap(st('STATUS_IN_PROGRESS','in',1),ago(34*60)),NOW);assert.equal(s.state,'stale');assert.equal(s.label,'SCORING UPDATE DELAYED');assert.notEqual(s.state,'live');assert.equal(liveState(snap(st('STATUS_IN_PROGRESS','in',1),ago(2*3600)),NOW).state,'unavailable');});
test('live: freshness threshold boundary',()=>{assert.equal(freshness({fetched_at:ago(FRESH_SECONDS)},NOW).freshness,'fresh');assert.equal(freshness({fetched_at:ago(FRESH_SECONDS+1)},NOW).freshness,'stale');});
test('live: in-progress status without any posted score is not live',()=>{assert.equal(liveState(snap(st('STATUS_IN_PROGRESS','in',1),ago(60),[P({thru:0,rounds:[{round:1,strokes:null,to_par:null}],total_to_par:null})]),NOW).state,'pre');});
test('live: final is final; suspended renders honestly',()=>{assert.equal(liveState(snap(st('STATUS_FINAL','post',4,true),ago(3*3600)),NOW).state,'final');const s=liveState(snap(st('STATUS_SUSPENDED','in',2),ago(60)),NOW);assert.equal(s.state,'suspended');assert.equal(s.label,'PLAY SUSPENDED');assert.equal(liveState(snap(st('STATUS_SUSPENDED','in',2),ago(40*60)),NOW).state,'stale');});
test('live: competitor normalization keeps nulls null and never invents a hole',()=>{
 const pre=normalizeCompetitor('1',{period:1,type:{name:'STATUS_SCHEDULED'},teeTime:'2026-10-02T13:00Z',startHole:10},{items:[{period:1,value:null,displayValue:null}]});
 assert.equal(pre.thru,null);assert.equal(pre.today_to_par,null);assert.equal(pre.total_to_par,null);assert.equal(pre.hole,null);assert.equal(pre.tee_time,'2026-10-02T13:00Z');assert.equal(pre.rounds[0].strokes,null);
 const mid=normalizeCompetitor('2',{period:1,thru:9,hole:9,startHole:1,position:{id:'14',displayName:'T14',isTie:true},type:{name:'STATUS_IN_PROGRESS'}},{items:[{period:1,value:31,displayValue:'-5',linescores:Array.from({length:9},(_,i)=>({period:i+1,value:3,par:4,scoreType:{name:'BIRDIE'}}))}]});
 assert.equal(mid.position_display,'T14');assert.equal(mid.tied,true);assert.equal(mid.total_to_par,-5);assert.equal(mid.today_to_par,-5);assert.equal(mid.rounds[0].complete,false);assert.equal(mid.holes.length,9);
 const lpga=normalizeCompetitor('3',{period:1,thru:17,startHole:10,position:{id:'1',displayName:'T1',isTie:true},type:{name:'STATUS_IN_PROGRESS'}},{items:[{period:1,value:62,displayValue:'-5'}]});
 assert.equal(lpga.holes,null);assert.equal(lpga.hole,null);assert.equal(lpga.total_to_par,-5);
 const cut=normalizeCompetitor('4',{period:2,thru:18,type:{name:'STATUS_CUT'}},{items:[{period:1,value:74,displayValue:'+3'},{period:2,value:75,displayValue:'+4'}]});assert.equal(cut.status,'cut');assert.equal(cut.total_to_par,7);
});
test('live: to-par parsing never turns junk or null into zero',()=>{assert.equal(toParNum(null),null);assert.equal(toParNum('-'),null);assert.equal(toParNum('E'),0);assert.equal(toParNum('−3'),-3);assert.equal(toParNum('+2'),2);});
test('live: leaders and ordering do not prefer a division',()=>{const s=snap(st('STATUS_IN_PROGRESS','in',1),ago(60),[P({slug:'a',total_to_par:-6,position_num:1}),P({slug:'b',total_to_par:-6,position_num:1,tied:true}),P({slug:'c',total_to_par:-4,position_num:3})]);const l=leaders(s);assert.equal(l.leaders.length,2);assert.equal(l.within2,3);
 const ev=[{state:'live',players:30,edition:{name:'Women'}},{state:'live',players:120,edition:{name:'Men'}},{state:'pre',players:150,edition:{name:'Z'}}];assert.deepEqual(orderEvents(ev).map(e=>e.edition.name),['Men','Women','Z']);
 const pub=publicEvent(s,NOW);assert.equal(pub.state,'live');assert.equal(pub.leaderboard[0].today_strokes,31);});
test('live snapshots: normalized insert-only rows keep nulls, valid statuses and deterministic ids',async()=>{const {snapshotRows}=await import('../workers/golf-ingest/src/live.js');
 const snap={edition:{id:'e1'},fetched_at:'2026-10-02T00:00:00Z',source_updated_at:null,capture_id:null,parser:'p',event_status:{name:'STATUS_IN_PROGRESS',state:'in',period:1},players:[{espn_id:'1',player_id:'p1',position_num:1,tied:true,position_display:'T1',total_to_par:-6,today_to_par:-6,thru:18,current_round:1,status:'active'},{espn_id:'2',player_id:null,position_num:null,tied:null,position_display:null,total_to_par:null,today_to_par:null,thru:null,current_round:1,status:'active'}]};
 const a=await snapshotRows(snap),b=await snapshotRows(snap);assert.equal(a.header.id,b.header.id);assert.equal(a.hash,b.hash);
 assert.equal(a.rows[1].score_to_par,null);assert.equal(a.rows[1].thru,null);assert.equal(a.rows[1].position,null);assert.ok(a.rows.every(r=>['active','cut','withdrawn','disqualified','dns'].includes(r.status)));
 const moved=structuredClone(snap);moved.players[0].thru=17;assert.notEqual((await snapshotRows(moved)).hash,a.hash);});
test('movement chart: observed points only, ties share one label, no data -> no chart',async()=>{const {movementChart,movementSeries}=await import('../src/lib/movement.js');
 assert.equal(movementChart([]),'');assert.equal(movementChart([{t:'2026-10-01T20:00:00Z',round:1,top:[{slug:'a',name:'A One',pos:1}]}]),'');
 const pts=[{t:'2026-10-01T20:00:00Z',round:1,top:[{slug:'a',name:'A One',pos:1,tied:false},{slug:'b',name:'B Two',pos:2,tied:true},{slug:'c',name:'C Three',pos:2,tied:true}]},{t:'2026-10-01T21:00:00Z',round:1,top:[{slug:'a',name:'A One',pos:2,tied:true},{slug:'b',name:'B Two',pos:1,tied:false},{slug:'c',name:'C Three',pos:2,tied:true}]}];
 const m=movementSeries(pts);assert.equal(m.series.length,3);assert.deepEqual(m.series.find(s=>s.key==='a').obs.map(o=>o.pos),[1,2]);
 const svg=movementChart(pts);assert.equal((svg.match(/class="mv-pt"/g)||[]).length,6);assert.match(svg,/T2 · One, Three|T2 · Three, One/);});
test('live persistence: unchanged boards are not stored, the 600 cap holds, missing tables degrade',async()=>{const {persistSnapshot,SNAPSHOT_CAP}=await import('../workers/golf-ingest/src/live.js');
 const kv=new Map(),env={STATE:{get:async k=>kv.get(k)??null,put:async(k,v)=>{kv.set(k,v);},delete:async k=>{kv.delete(k);}}};const posts=[];
 const db=async(t,q,o)=>{if(o?.method==='POST')posts.push(t);return null;};
 const snap=(thru,at)=>({edition:{id:'e1'},fetched_at:at,source_updated_at:null,parser:'p',event_status:{name:'STATUS_IN_PROGRESS',state:'in',period:1},players:[{espn_id:'1',player_id:null,position_num:1,tied:false,position_display:'1',total_to_par:-3,today_to_par:-3,thru,current_round:1,status:'active'}]});
 assert.equal((await persistSnapshot(env,db,snap(9,'2026-10-02T00:00:00Z'))).stored,true);
 assert.equal((await persistSnapshot(env,db,snap(9,'2026-10-02T00:10:00Z'))).reason,'unchanged');
 assert.equal((await persistSnapshot(env,db,snap(10,'2026-10-02T00:20:00Z'))).stored,true);
 assert.deepEqual(posts.filter(t=>t==='golf_live_snapshots').length,2);
 kv.set('live:db:last:e1',JSON.stringify({hash:'x',count:SNAPSHOT_CAP}));assert.equal((await persistSnapshot(env,db,snap(11,'2026-10-02T00:30:00Z'))).reason,'cap_reached');
 kv.delete('live:db:last:e1');const missing=async()=>{throw Error('sports_http_404:golf_live_snapshots:{"code":"PGRST205"}');};
 assert.equal((await persistSnapshot(env,missing,snap(12,'2026-10-02T00:40:00Z'))).reason,'tables_not_migrated');assert.equal(kv.get('live:db:missing'),'1');});
test('movement acceptance: status transitions, round scoping, rail = chart, sparse stays sparse',async()=>{const {movementPoint}=await import('../workers/golf-ingest/src/live.js');const {movementChart,movementSeries}=await import('../src/lib/movement.js');
 const P=(id,pos,status='active',tied=false)=>({espn_id:id,slug:'p'+id,name:'Player '+id,position_num:pos,tied,total_to_par:-pos,thru:9,status});
 const s1={fetched_at:'2026-10-02T15:00:00Z',event_status:{period:2,name:'STATUS_IN_PROGRESS'},players:[P('1',1),P('2',2,'active',true),P('3',2,'active',true),P('4',4)]};
 const s2={fetched_at:'2026-10-02T16:00:00Z',event_status:{period:2,name:'STATUS_IN_PROGRESS'},players:[P('1',1),P('2',null,'withdrawn'),P('3',2),P('4',3,'cut')]};
 const a=movementPoint(s1),b=movementPoint(s2);
 assert.deepEqual(b.top.map(x=>x.slug),['p1','p3']);assert.equal(a.top.find(x=>x.slug==='p2').tied,true);
 const m=movementSeries([a,b]);assert.ok(!m.series.some(s=>s.key==='p2'),'withdrawn player is not drawn as continuing');assert.equal(m.series.find(s=>s.key==='p3').obs.map(o=>o.pos).join(),'2,2');
 const svgFull=movementChart([a,b]),svgRail=movementChart([a,b],{compact:true});const n=s=>(s.match(/class="mv-pt"/g)||[]).length;assert.equal(n(svgFull),n(svgRail));
 assert.equal(n(svgFull),m.series.reduce((x,s)=>x+s.obs.filter(Boolean).length,0),'one marker per observation, none interpolated');
 assert.match(svgFull,/Markers are observations; dotted links are not positions/);assert.match(svgFull,/class="mv-link"/);
 const rounds=[{...a,round:1},{...b,round:2},{...b,t:'2026-10-02T17:00:00Z',round:2}];assert.equal(rounds.filter(x=>x.round===2).length,2);});
test('live: ESPN end-of-round PLAY_COMPLETE (completed:true, post) is a round state, never FINAL',async()=>{const {isEventFinal,liveState}=await import('../workers/shared/live.js');const {parseEventBundle}=await import('../workers/golf-ingest/src/espn.js');
 assert.equal(isEventFinal({name:'STATUS_PLAY_COMPLETE',state:'post',completed:true}),false);assert.equal(isEventFinal({name:'STATUS_FINAL',completed:true}),true);
 const s=liveState({fetched_at:new Date(Date.now()-60000).toISOString(),event_status:{name:'STATUS_PLAY_COMPLETE',state:'post',completed:false,period:1},players:[{thru:18,rounds:[{round:1,strokes:63}]}]});assert.equal(s.state,'round_complete');
 const b={league:'pga',event_id:'1',event:{name:'X',status:{type:{completed:true}},courses:[]},comp_status:{period:1,type:{name:'STATUS_PLAY_COMPLETE',state:'post',completed:true}},competitors:[{id:'a',linescores:{items:[{period:1,value:63,displayValue:'-8',linescores:Array.from({length:18},(_,i)=>({period:i+1,value:3}))}]}}]};
 const p=parseEventBundle(b);assert.equal(p.event.completed,false);assert.equal(p.rows[0].finish_status,'unknown');assert.equal(p.rows[0].rounds.length,1);});
