import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import api from '../workers/golf-api/src/index.js';import ingest from '../workers/golf-ingest/src/index.js';
import {store,stableId} from '../workers/shared/store.js';import {day,single,planGraph} from '../workers/golf-ingest/src/wikidata.js';
test('SPORTS target refuses identity/billing credentials',()=>{assert.equal(store({SPORTS_URL:'https://rlfyavnhbngwbldebrid.supabase.co',SPORTS_KEY:'test'}),null);});
test('empty successful database writes do not become JSON parser failures',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>new Response('',{status:201});try{const db=store({SPORTS_URL:'https://tkmlnhmylqnttmnsnief.supabase.co',SPORTS_KEY:'test'});assert.equal(await db('golf_sources','',{method:'POST',body:'{}'}),null);}finally{globalThis.fetch=original;}});
test('unscoped database table is denied before request',async()=>{const db=store({SPORTS_URL:'https://tkmlnhmylqnttmnsnief.supabase.co',SPORTS_KEY:'test'});await assert.rejects(db('pbe_sport_entitlements'),/golf_scope_required/);});
test('date precision never expands a year or month into a fabricated day',()=>{assert.equal(day({time:'+2025-00-00T00:00:00Z',precision:9}),null);assert.equal(day({time:'+2025-04-00T00:00:00Z',precision:10}),null);assert.equal(day({time:'+2026-04-09T00:00:00Z',precision:11}),'2026-04-09');});
test('ambiguous source statements do not select an arbitrary winner',()=>{const c=value=>({rank:'normal',mainsnak:{snaktype:'value',datavalue:{value}}});assert.equal(single({claims:{P1346:[c({id:'Q1'}),c({id:'Q2'})]}},'P1346'),null);});
test('identity without golf classification is held rather than merged',async()=>{const e={id:'Q30161386',capture_id:'unit-capture',labels:{en:{value:'Scottie Scheffler'}},claims:{P31:[{rank:'normal',mainsnak:{snaktype:'value',datavalue:{value:{id:'Q5'}}}}]}};const plan=await planGraph({Q30161386:e});assert(plan.held.some(h=>h.reason==='identity_requires_human_golf_birth_date'));assert(!plan.rows.some(r=>r.table==='golf_players'));assert(plan.rows.some(r=>r.table==='golf_identity_queue'));});
test('deterministic row keys remain UUIDs and never merge by name',async()=>{assert.equal(await stableId('golf_players:Q30161386'),await stableId('golf_players:Q30161386'));assert.notEqual(await stableId('golf_players:Q30161386'),await stableId('golf_players:Q380613'));});
test('admin ingestion cannot be triggered anonymously',async()=>{const r=await ingest.fetch(new Request('https://internal/admin/bootstrap',{method:'POST'}),{});assert.equal(r.status,401);});
test('premium gate does not read SPORTS before authorization',async()=>{const original=globalThis.fetch;let reads=0;globalThis.fetch=async()=>{reads++;throw Error('unexpected read');};try{const r=await api.fetch(new Request('https://golf.test/v1/intelligence/player-dna/rory-mcilroy-q380613'),{SPORTS_URL:'https://tkmlnhmylqnttmnsnief.supabase.co',SPORTS_KEY:'test'});assert.equal(r.status,403);assert.equal(reads,0);assert(!('data' in await r.json()));}finally{globalThis.fetch=original;}});
test('runtime SQL parses with no security-definer privilege escalation',async()=>{const sql=await fs.readFile('scripts/runtime-schema.sql','utf8');const {parse}=await import('pgsql-parser');assert((await parse(sql)).stmts.length>0);assert(!/security definer/i.test(sql));assert(sql.includes('unapproved capture'));assert(sql.includes('golf_source_changes'));});

test('production CSP permits network GA4 script, collection and image transports',async()=>{const config=JSON.parse(await fs.readFile('vercel.json','utf8'));const policy=config.headers[0].headers.find(h=>h.key==='Content-Security-Policy').value;for(const directive of ['script-src','connect-src','img-src'])assert(policy.split(';').find(p=>p.trim().startsWith(directive+' ')).includes('https://www.googletagmanager.com'));assert(!policy.includes('unsafe-inline'));});

test('premium routes never read the projection before authorization',async()=>{let reads=0;const PUBLIC={get:async()=>{reads++;return null;}};for(const m of ['player-dna/x','course-dna/x','course-fit/x/y','field/x','matchups/a/b']){const r=await api.fetch(new Request('https://golf.test/v1/intelligence/'+m),{PUBLIC});assert.equal(r.status,403);}assert.equal(reads,0);});
test('vercel proxies API same-origin and rewrites unprerendered matchups',async()=>{const c=JSON.parse(await fs.readFile('vercel.json','utf8'));assert(c.rewrites.some(r=>r.source==='/api/:path*'&&r.destination==='https://golf-api.propbetedge.ai/:path*'));assert(c.rewrites.some(r=>r.source==='/matchups/:a/:b'&&r.destination==='/matchup-view'));});
