import test from 'node:test';import assert from 'node:assert/strict';
import {parseFeed,classify,buildResolver,resolve} from '../workers/golf-ingest/src/video.js';
import registry from '../data/source-registry/youtube-channels.json' with {type:'json'};
const ix={players:[{slug:'scottie-scheffler-q1',name:'Scottie Scheffler'},{slug:'jacob-bridgeman-q2',name:'Jacob Bridgeman'},{slug:'john-smith-a',name:'John Smith'},{slug:'john-smith-b',name:'John Smith'}],
 editions:[{slug:'biltmore-2026',year:2026,tournament:{name:'Biltmore Championship Asheville'},starts_on:'2026-09-17',ends_on:'2026-09-20',course:{slug:'cliffs'}},{slug:'masters-2019',year:2019,tournament:{name:'Masters Tournament'},starts_on:'2019-04-11',ends_on:'2019-04-14',course:{slug:'augusta'}},{slug:'masters-2026',year:2026,tournament:{name:'Masters Tournament'},starts_on:'2026-04-09',ends_on:'2026-04-12',course:{slug:'augusta'}}]};
test('video: Atom feed parses ids, dates and shorts',()=>{const f=parseFeed('<feed><title>PGA Tour</title><entry><yt:videoId>abc123</yt:videoId><yt:channelId>UCx</yt:channelId><title>Round 2 Highlights | Biltmore Championship Asheville &amp; more</title><link rel="alternate" href="https://www.youtube.com/watch?v=abc123"/><published>2026-09-19T01:00:00+00:00</published><media:thumbnail url="https://i.ytimg.com/vi/abc123/hqdefault.jpg"/></entry><entry><yt:videoId>s1</yt:videoId><title>Wow 😮</title><link rel="alternate" href="https://www.youtube.com/shorts/s1"/><published>2026-09-19T02:00:00+00:00</published></entry></feed>');
 assert.equal(f.feed_title,'PGA Tour');assert.equal(f.entries.length,2);assert.equal(f.entries[0].title,'Round 2 Highlights | Biltmore Championship Asheville & more');assert.equal(f.entries[1].is_short,true);});
test('video: classification families',()=>{assert.equal(classify('Full Final Round | 2026 Masters').video_type,'full_round');assert.equal(classify('Round 3 Highlights | Biltmore').video_type,'round_highlights');assert.equal(classify("What's in the Bag: Scottie Scheffler").video_type,'witb');assert.equal(classify('Jacob Bridgeman press conference').video_type,'press_conference');assert.equal(classify('Hole-in-one on 16!').video_type,'shot_highlights');assert.equal(classify('Augusta National flyover').video_type,'course_flyover');assert.equal(classify('So close 😩').video_type,'other');});
test('video: entities resolve in the video’s own historical context; namesakes never match',()=>{const R=buildResolver(ix);
 const a=resolve({title:'Jacob Bridgeman Round 4 Highlights | Biltmore Championship Asheville',published_at:'2026-09-21T00:00:00Z',video_type:'round_highlights'},R);assert.deepEqual(a.editions,['biltmore-2026']);assert.deepEqual(a.players,['jacob-bridgeman-q2']);assert.equal(a.round,4);assert.equal(a.confidence,'high');assert.deepEqual(a.courses,['cliffs']);
 const h=resolve({title:'Classic: Tiger at the 2019 Masters final round',published_at:'2026-04-05T00:00:00Z',video_type:'historical'},R);assert.deepEqual(h.editions,['masters-2019']);assert.equal(h.basis,'title_year');
 const n=resolve({title:'John Smith highlights',published_at:'2026-09-21T00:00:00Z',video_type:'player_highlights'},R);assert.deepEqual(n.players,[]);assert.equal(n.confidence,'low');
 const far=resolve({title:'Biltmore Championship Asheville preview',published_at:'2027-03-01T00:00:00Z',video_type:'course_preview'},R);assert.deepEqual(far.editions,[]);});
test('video: registry enables only doubly-proven official channels; fan or unproven channels stay off',()=>{for(const c of registry.channels){if(c.enabled){assert.ok(c.id?.startsWith('UC'));assert.ok(c.verification.checks.includes('feed_title_match'));assert.ok(c.verification.checks.some(x=>x==='verified_badge'||x.startsWith('linked_from_official_site')));}else assert.ok(c.verification.hold);}
 assert.ok(!registry.channels.some(c=>c.id==='UC_ISrZjdrW6wapPpA5VrArQ'&&c.enabled));});
