/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/golf-api/wrangler.jsonc --include-runtime=false workers/golf-api/worker-configuration.d.ts` (hash: a73c390ec4366cf9aa15afb702198622)
interface __BaseEnv_Env {
	AUTH: Fetcher /* propbetedge-auth-magic */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
