import fs from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {store,upsert} from '../workers/shared/store.js';
const root=process.cwd();
export async function sportsEnv(){
 const text=await fs.readFile('D:/Workers/secrets/soccer-supabase.env','utf8');
 const vars=Object.fromEntries(text.split(/\r?\n/).filter(x=>/^[A-Z_]+=/.test(x)).map(x=>{const i=x.indexOf('=');return [x.slice(0,i),x.slice(i+1).replace(/^['"]|['"]$/g,'')]}));
 const env={SPORTS_URL:vars.SOCCER_MODEL_SUPABASE_URL,SPORTS_KEY:vars.SOCCER_MODEL_SUPABASE_SERVICE_ROLE_KEY};
 if(env.SPORTS_URL!=='https://tkmlnhmylqnttmnsnief.supabase.co'||!env.SPORTS_KEY)throw Error('SPORTS target guard');
 return env;
}
export async function cf(path,options={}){
 const t=await fs.readFile('C:/Users/goodl/.wrangler/config/default.toml','utf8');
 const token=t.match(/oauth_token\s*=\s*"([^"]+)"/)?.[1];if(!token)throw Error('Cloudflare authentication missing');
 const r=await fetch('https://api.cloudflare.com/client/v4/'+path,{...options,headers:{authorization:'Bearer '+token,'content-type':'application/json',...options.headers},signal:AbortSignal.timeout(30000)});
 const b=await r.json();if(!b.success)throw Error(JSON.stringify(b.errors));return b.result;
}
export const account='fd3a233edadd0a60916413c1199f71ee';
if(process.argv[2]==='inspect'){
 const [scripts,buckets,zones]=await Promise.all([cf(`accounts/${account}/workers/scripts`),cf(`accounts/${account}/r2/buckets`),cf('zones?name=propbetedge.ai')]);
 console.log(JSON.stringify({workers:scripts.filter(x=>/golf|auth-magic/.test(x.id)).map(x=>({id:x.id,modified_on:x.modified_on})),buckets,zones:zones.map(x=>({id:x.id,name:x.name}))},null,2));
}
if(process.argv[2]==='secrets'){
 const env=await sportsEnv();
 try{env.ADMIN_TOKEN=await fs.readFile('D:/Workers/secrets/golf-admin-token','utf8');}catch{env.ADMIN_TOKEN=crypto.randomUUID()+crypto.randomUUID();await fs.writeFile('.golf-admin-token',env.ADMIN_TOKEN);}
 await fs.writeFile('.golf-secrets.json',JSON.stringify(env));
 try{for(const name of ['golf-api','golf-ingest','golf-news']){const r=spawnSync(process.execPath,['node_modules/wrangler/bin/wrangler.js','secret','bulk','.golf-secrets.json','--config',`workers/${name}/wrangler.jsonc`],{stdio:'inherit',cwd:root});if(r.status!==0)throw Error('secret configuration failed');}}finally{await fs.unlink('.golf-secrets.json');}
}
if(process.argv[2]==='seed'){
 const db=store(await sportsEnv());
 await upsert(db,'golf_sources',[{id:'wikidata',name:'Wikidata structured golf metadata',owner:'Wikimedia Foundation / contributors',verdict:'APPROVED',registry_version:'golf-sources/2',terms_url:'https://www.wikidata.org/wiki/Wikidata:Licensing',automated_access:true,rights_assessment:{licence:'CC0-1.0',scope:'bounded structured identities, venue metadata, edition dates and winner assertions; no Wikipedia prose/media or live feed',redistribution:'CC0 structured data public and commercial reuse; source attribution supplied',cadence:'manual bounded bootstrap; minimum daily automated cadence if later enabled',identity:'QID + human + golf + day-precision DOB; distinct source IDs never name merge',corrections:'new raw capture, new source capture, transactional field revision ledger'},reviewed_at:new Date().toISOString()}]);
 await upsert(db,'golf_sources',[
  {id:'wikipedia',name:'Wikipedia golf championship and tour articles',owner:'Wikimedia Foundation / contributors',verdict:'APPROVED',registry_version:'golf-sources/3',terms_url:'https://en.wikipedia.org/wiki/Wikipedia:Reusing_Wikipedia_content',automated_access:true,rights_assessment:{licence:'CC BY-SA 4.0',owner_approval:'2026-10-01 owner approved CC BY-SA results source (attribution + share-alike notice on redistributed results dataset)',scope:'leaderboards, round scores, fields, cut lines, course setup tables, tour season schedules via documented MediaWiki API',identity:'linked article title -> Wikidata QID via pageprops; unlinked rows held; never name-merged',cadence:'results every 6h for recent editions, 30d for completed history (revision-checked); schedules every 6h',corrections:'new capture per revision, typed comparison, golf_source_changes ledger'},reviewed_at:new Date().toISOString()},
  {id:'espn',name:'ESPN Golf core API',owner:'ESPN Enterprises, Inc.',verdict:'APPROVED',registry_version:'golf-sources/4',terms_url:'https://disneytermsofuse.com/',automated_access:true,rights_assessment:{owner_approval:'2026-10-01 owner approved ESPN as an additional Golf source (supersedes earlier hold)',scope:'sports.core.api.espn.com golf leagues: events, courses, competitors, linescores (rounds, holes, tee times), athlete profiles, season statistics',excluded:'site.api.espn.com returns 403 to our identified client and is not used; no auth/bot bypass; no private refs',identity:'ESPN athlete id crosswalk; joins canonical players only on exact name + birth date or same-edition corroboration; ambiguous held',merge:'field-level; existing values never overwritten; disagreements recorded as conflicts'},reviewed_at:new Date().toISOString()},
  {id:'espn-live',name:'ESPN Golf core API (live event snapshots)',owner:'ESPN',verdict:'APPROVED',registry_version:'golf-sources/4',terms_url:'https://disneytermsofuse.com/',automated_access:true,rights_assessment:{licence:'Owner approved ESPN as a Golf source 2026-10-01',scope:'current-event status, competitor status, positions, thru, round and hole scores, tee times from sports.core.api.espn.com only',identity:'ESPN athlete crosswalk; unmapped athletes shown by ESPN name without a profile link',cadence:'every 10 minutes for editions in the current window'},reviewed_at:new Date().toISOString()},
  {id:'youtube',name:'YouTube public channel feeds + oEmbed (keyless)',owner:'Google / channel owners',verdict:'APPROVED',registry_version:'golf-sources/4',terms_url:'https://www.youtube.com/t/terms',automated_access:true,rights_assessment:{licence:'Embedding via the standard YouTube player only; no download, rehost or clipping',scope:'public Atom feeds of verified official channels (data/source-registry/youtube-channels.json) and oEmbed embeddability checks',identity:'channel ids proven by feed title plus verified badge or official-site link',cadence:'every 30 minutes'},reviewed_at:new Date().toISOString()},
  {id:'metno',name:'MET Norway Locationforecast 2.0',owner:'Norwegian Meteorological Institute',verdict:'APPROVED',registry_version:'golf-sources/4',terms_url:'https://api.met.no/doc/TermsOfService',automated_access:true,rights_assessment:{licence:'CC BY 4.0 (attribution required; commercial use permitted)',scope:'hourly forecasts for tournament venues outside NWS coverage',identity:'venue coordinates from the venue-coordinate registry (course or locality, labelled)',cadence:'every 3 hours, honouring Expires; identifying User-Agent; far below 20 req/s'},reviewed_at:new Date().toISOString()},
  {id:'nws',name:'NOAA National Weather Service API',owner:'U.S. National Weather Service',verdict:'APPROVED',registry_version:'golf-sources/4',terms_url:'https://www.weather.gov/disclaimer',automated_access:true,rights_assessment:{licence:'U.S. government work, public domain',scope:'hourly forecasts and gridpoint gusts for US course coordinates',identity:'course coordinates from Wikidata (verified golf venue)',cadence:'every 3 hours for editions ending within 8 days'},reviewed_at:new Date().toISOString()},
  {id:'commons',name:'Wikimedia Commons entity photographs',owner:'Wikimedia Commons contributors',verdict:'APPROVED',registry_version:'golf-sources/3',terms_url:'https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia',automated_access:true,rights_assessment:{licence:'per file: CC0, public domain, CC BY, CC BY-SA (owner approved 2026-10-01); NC/ND/GFDL-only/fair use rejected',identity:'file must be the P18 image of the entity canonical Wikidata crosswalk; no name matching',attribution:'author, licence, licence URL, source page shown with every image',derivatives:'resize only (AVIF/WebP), no crops or edits'},reviewed_at:new Date().toISOString()}
 ]);
 for(const [source_id,parser_version,cadence_seconds] of [['wikidata','wikidata-wdqs-golf/1.0.0',86400],['wikipedia','wikipedia-golf/1.0.0',86400],['commons','commons-review/1',86400],['espn','espn-golf/1.0.0',86400],['nws','nws-hourly/1.0.0',86400],['espn-live','espn-golf-live/1.0.0',86400],['youtube','golf-youtube-feed/1.0.0',86400],['metno','nws-hourly/1.0.0',86400]]){const state=await db('golf_source_state','source_id=eq.'+source_id);if(!state.length)await upsert(db,'golf_source_state',[{source_id,parser_version,cadence_seconds}],'source_id');else await db('golf_source_state','source_id=eq.'+source_id,{method:'PATCH',body:JSON.stringify({parser_version})});}
 console.log('Wikidata metadata registry and durable source state configured in SPORTS');
}
if(['bootstrap','shadow'].includes(process.argv[2])){
 const token=await fs.readFile('D:/Workers/secrets/golf-admin-token','utf8');const r=await fetch('https://golf-api.propbetedge.ai/admin/'+(process.argv[2]==='shadow'?'news-shadow':'bootstrap'),{method:'POST',headers:{authorization:'Bearer '+token},signal:AbortSignal.timeout(90000)});console.log(r.status,await r.text());
}
